stages:
  - build
  - test

compile:
  stage: build
  tags:
    - nix
  script:
    - nix develop .#pipeline --command bash -c "zig build -Doptimize=Debug --summary all"
    - nix develop .#pipeline --command bash -c "zig build -Doptimize=ReleaseSafe --summary all"
    - nix develop .#pipeline --command bash -c "zig build -Doptimize=ReleaseFast --summary all"
    - nix develop .#pipeline --command bash -c "zig build -Doptimize=ReleaseSmall --summary all"
  cache:
    key: build-cache
    paths:
      - .zig-cache/

tests:
  stage: test
  tags:
    - nix
  script:
    - nix develop .#pipeline --command bash -c "zig build unit-test --summary all"
    - nix develop .#pipeline --command bash -c "zig build integration -Dgc-stress -Dintegration-verbose"
  cache:
    key: build-cache
    paths:
      - .zig-cache/
