stages:
  - test

tests:
  stage: test
  script:
    - nix develop .#pipeline --command bash -c "zig build check -Doptimize=Debug --summary all"
    - nix develop .#pipeline --command bash -c "zig build check -Doptimize=ReleaseSafe --summary all"
    - nix develop .#pipeline --command bash -c "zig build check -Doptimize=ReleaseFast --summary all"
    - nix develop .#pipeline --command bash -c "zig build check -Doptimize=ReleaseSmall --summary all"
    - nix develop .#pipeline --command bash -c "zig build unit-test --summary all"
    - nix develop .#pipeline --command bash -c "zig build integration -Dintegration-verbose"
  tags:
    - nix
