stages:
  - test

tests:
  stage: test
  script:
    - nix develop .#pipeline --command bash -c "zig build check --summary all"
    - nix develop .#pipeline --command bash -c "zig build unit-test --summary all"
    - nix develop .#pipeline --command bash -c "zig build integration -Dintegration-verbose"
  tags:
    - nix

