#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 96
#define LARGE_STATE_COUNT 16
#define SYMBOL_COUNT 53
#define ALIAS_COUNT 0
#define TOKEN_COUNT 33
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define PRODUCTION_ID_COUNT 1

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_var = 2,
  anon_sym_const = 3,
  anon_sym_EQ = 4,
  anon_sym_SEMI = 5,
  anon_sym_LBRACE = 6,
  anon_sym_RBRACE = 7,
  anon_sym_if = 8,
  anon_sym_else = 9,
  anon_sym_print = 10,
  anon_sym_DASH = 11,
  anon_sym_BANG = 12,
  anon_sym_SLASH = 13,
  anon_sym_STAR = 14,
  anon_sym_PLUS = 15,
  anon_sym_DOT = 16,
  anon_sym_LT = 17,
  anon_sym_LT_EQ = 18,
  anon_sym_GT_EQ = 19,
  anon_sym_GT = 20,
  anon_sym_BANG_EQ = 21,
  anon_sym_EQ_EQ = 22,
  anon_sym_and = 23,
  anon_sym_or = 24,
  sym_number = 25,
  sym_string = 26,
  anon_sym_true = 27,
  anon_sym_false = 28,
  sym_null = 29,
  anon_sym_COLON = 30,
  anon_sym_SLASH_SLASH = 31,
  aux_sym_comment_token1 = 32,
  sym_source_file = 33,
  sym__declaration = 34,
  sym_varDeclaration = 35,
  sym__statement = 36,
  sym_block = 37,
  sym_ifStatement = 38,
  sym_expressionStatement = 39,
  sym_printStatement = 40,
  sym__expression = 41,
  sym_unary = 42,
  sym_binary = 43,
  sym_comparison = 44,
  sym_equality = 45,
  sym_logical = 46,
  sym_assignment = 47,
  sym__primary = 48,
  sym_bool = 49,
  sym_typeHint = 50,
  sym_comment = 51,
  aux_sym_source_file_repeat1 = 52,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_var] = "var",
  [anon_sym_const] = "const",
  [anon_sym_EQ] = "=",
  [anon_sym_SEMI] = ";",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_if] = "if",
  [anon_sym_else] = "else",
  [anon_sym_print] = "print",
  [anon_sym_DASH] = "-",
  [anon_sym_BANG] = "!",
  [anon_sym_SLASH] = "/",
  [anon_sym_STAR] = "*",
  [anon_sym_PLUS] = "+",
  [anon_sym_DOT] = ".",
  [anon_sym_LT] = "<",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_GT] = ">",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_and] = "and",
  [anon_sym_or] = "or",
  [sym_number] = "number",
  [sym_string] = "string",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_null] = "null",
  [anon_sym_COLON] = ":",
  [anon_sym_SLASH_SLASH] = "//",
  [aux_sym_comment_token1] = "comment_token1",
  [sym_source_file] = "source_file",
  [sym__declaration] = "_declaration",
  [sym_varDeclaration] = "varDeclaration",
  [sym__statement] = "_statement",
  [sym_block] = "block",
  [sym_ifStatement] = "ifStatement",
  [sym_expressionStatement] = "expressionStatement",
  [sym_printStatement] = "printStatement",
  [sym__expression] = "_expression",
  [sym_unary] = "unary",
  [sym_binary] = "binary",
  [sym_comparison] = "comparison",
  [sym_equality] = "equality",
  [sym_logical] = "logical",
  [sym_assignment] = "assignment",
  [sym__primary] = "_primary",
  [sym_bool] = "bool",
  [sym_typeHint] = "typeHint",
  [sym_comment] = "comment",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_var] = anon_sym_var,
  [anon_sym_const] = anon_sym_const,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_else] = anon_sym_else,
  [anon_sym_print] = anon_sym_print,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_and] = anon_sym_and,
  [anon_sym_or] = anon_sym_or,
  [sym_number] = sym_number,
  [sym_string] = sym_string,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_null] = sym_null,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_SLASH_SLASH] = anon_sym_SLASH_SLASH,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [sym_source_file] = sym_source_file,
  [sym__declaration] = sym__declaration,
  [sym_varDeclaration] = sym_varDeclaration,
  [sym__statement] = sym__statement,
  [sym_block] = sym_block,
  [sym_ifStatement] = sym_ifStatement,
  [sym_expressionStatement] = sym_expressionStatement,
  [sym_printStatement] = sym_printStatement,
  [sym__expression] = sym__expression,
  [sym_unary] = sym_unary,
  [sym_binary] = sym_binary,
  [sym_comparison] = sym_comparison,
  [sym_equality] = sym_equality,
  [sym_logical] = sym_logical,
  [sym_assignment] = sym_assignment,
  [sym__primary] = sym__primary,
  [sym_bool] = sym_bool,
  [sym_typeHint] = sym_typeHint,
  [sym_comment] = sym_comment,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_var] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_const] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_print] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_and] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_or] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_null] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_SLASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__declaration] = {
    .visible = false,
    .named = true,
  },
  [sym_varDeclaration] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_ifStatement] = {
    .visible = true,
    .named = true,
  },
  [sym_expressionStatement] = {
    .visible = true,
    .named = true,
  },
  [sym_printStatement] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_unary] = {
    .visible = true,
    .named = true,
  },
  [sym_binary] = {
    .visible = true,
    .named = true,
  },
  [sym_comparison] = {
    .visible = true,
    .named = true,
  },
  [sym_equality] = {
    .visible = true,
    .named = true,
  },
  [sym_logical] = {
    .visible = true,
    .named = true,
  },
  [sym_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym__primary] = {
    .visible = false,
    .named = true,
  },
  [sym_bool] = {
    .visible = true,
    .named = true,
  },
  [sym_typeHint] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 2,
  [4] = 2,
  [5] = 2,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 8,
  [11] = 6,
  [12] = 7,
  [13] = 13,
  [14] = 14,
  [15] = 14,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 34,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 34,
  [45] = 33,
  [46] = 31,
  [47] = 40,
  [48] = 34,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 49,
  [54] = 54,
  [55] = 55,
  [56] = 49,
  [57] = 50,
  [58] = 58,
  [59] = 51,
  [60] = 52,
  [61] = 49,
  [62] = 54,
  [63] = 55,
  [64] = 58,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 67,
  [69] = 69,
  [70] = 70,
  [71] = 69,
  [72] = 72,
  [73] = 70,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 75,
  [79] = 74,
  [80] = 77,
  [81] = 72,
  [82] = 66,
  [83] = 76,
  [84] = 65,
  [85] = 85,
  [86] = 85,
  [87] = 87,
  [88] = 87,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 93,
  [95] = 95,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(3);
      ADVANCE_MAP(
        '!', 9,
        '"', 1,
        '*', 11,
        '+', 12,
        '-', 8,
        '.', 13,
        '/', 10,
        ':', 24,
        ';', 5,
        '<', 14,
        '=', 4,
        '>', 17,
        '{', 6,
        '}', 7,
      );
      if (lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(20);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(22);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(21);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(19);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_BANG);
      if (lookahead == '=') ADVANCE(18);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '/') ADVANCE(25);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(15);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(16);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(29);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '/') ADVANCE(28);
      if (lookahead == '\r' ||
          lookahead == ' ') ADVANCE(27);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(29);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '/') ADVANCE(26);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(29);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(29);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ADVANCE_MAP(
        'a', 1,
        'c', 2,
        'e', 3,
        'f', 4,
        'i', 5,
        'n', 6,
        'o', 7,
        'p', 8,
        't', 9,
        'v', 10,
      );
      if (lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'n') ADVANCE(11);
      END_STATE();
    case 2:
      if (lookahead == 'o') ADVANCE(12);
      END_STATE();
    case 3:
      if (lookahead == 'l') ADVANCE(13);
      END_STATE();
    case 4:
      if (lookahead == 'a') ADVANCE(14);
      END_STATE();
    case 5:
      if (lookahead == 'f') ADVANCE(15);
      END_STATE();
    case 6:
      if (lookahead == 'u') ADVANCE(16);
      END_STATE();
    case 7:
      if (lookahead == 'r') ADVANCE(17);
      END_STATE();
    case 8:
      if (lookahead == 'r') ADVANCE(18);
      END_STATE();
    case 9:
      if (lookahead == 'r') ADVANCE(19);
      END_STATE();
    case 10:
      if (lookahead == 'a') ADVANCE(20);
      END_STATE();
    case 11:
      if (lookahead == 'd') ADVANCE(21);
      END_STATE();
    case 12:
      if (lookahead == 'n') ADVANCE(22);
      END_STATE();
    case 13:
      if (lookahead == 's') ADVANCE(23);
      END_STATE();
    case 14:
      if (lookahead == 'l') ADVANCE(24);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 16:
      if (lookahead == 'l') ADVANCE(25);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_or);
      END_STATE();
    case 18:
      if (lookahead == 'i') ADVANCE(26);
      END_STATE();
    case 19:
      if (lookahead == 'u') ADVANCE(27);
      END_STATE();
    case 20:
      if (lookahead == 'r') ADVANCE(28);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_and);
      END_STATE();
    case 22:
      if (lookahead == 's') ADVANCE(29);
      END_STATE();
    case 23:
      if (lookahead == 'e') ADVANCE(30);
      END_STATE();
    case 24:
      if (lookahead == 's') ADVANCE(31);
      END_STATE();
    case 25:
      if (lookahead == 'l') ADVANCE(32);
      END_STATE();
    case 26:
      if (lookahead == 'n') ADVANCE(33);
      END_STATE();
    case 27:
      if (lookahead == 'e') ADVANCE(34);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_var);
      END_STATE();
    case 29:
      if (lookahead == 't') ADVANCE(35);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_else);
      END_STATE();
    case 31:
      if (lookahead == 'e') ADVANCE(36);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_null);
      END_STATE();
    case 33:
      if (lookahead == 't') ADVANCE(37);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_const);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_print);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 27},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {(TSStateId)(-1)},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [sym_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_var] = ACTIONS(1),
    [anon_sym_const] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [anon_sym_print] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_and] = ACTIONS(1),
    [anon_sym_or] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_null] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
  [1] = {
    [sym_source_file] = STATE(91),
    [sym__declaration] = STATE(75),
    [sym_varDeclaration] = STATE(76),
    [sym__statement] = STATE(76),
    [sym_block] = STATE(58),
    [sym_ifStatement] = STATE(58),
    [sym_expressionStatement] = STATE(58),
    [sym_printStatement] = STATE(58),
    [sym__expression] = STATE(82),
    [sym_unary] = STATE(17),
    [sym_binary] = STATE(17),
    [sym_comparison] = STATE(17),
    [sym_equality] = STATE(17),
    [sym_logical] = STATE(17),
    [sym_assignment] = STATE(17),
    [sym__primary] = STATE(17),
    [sym_bool] = STATE(23),
    [sym_comment] = STATE(1),
    [aux_sym_source_file_repeat1] = STATE(9),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_identifier] = ACTIONS(7),
    [anon_sym_var] = ACTIONS(9),
    [anon_sym_const] = ACTIONS(9),
    [anon_sym_LBRACE] = ACTIONS(11),
    [anon_sym_if] = ACTIONS(13),
    [anon_sym_print] = ACTIONS(15),
    [anon_sym_DASH] = ACTIONS(17),
    [anon_sym_BANG] = ACTIONS(17),
    [sym_number] = ACTIONS(19),
    [sym_string] = ACTIONS(19),
    [anon_sym_true] = ACTIONS(21),
    [anon_sym_false] = ACTIONS(21),
    [sym_null] = ACTIONS(23),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
  [2] = {
    [sym__statement] = STATE(61),
    [sym_block] = STATE(58),
    [sym_ifStatement] = STATE(58),
    [sym_expressionStatement] = STATE(58),
    [sym_printStatement] = STATE(58),
    [sym__expression] = STATE(82),
    [sym_unary] = STATE(17),
    [sym_binary] = STATE(17),
    [sym_comparison] = STATE(17),
    [sym_equality] = STATE(17),
    [sym_logical] = STATE(17),
    [sym_assignment] = STATE(17),
    [sym__primary] = STATE(17),
    [sym_bool] = STATE(23),
    [sym_comment] = STATE(2),
    [sym_identifier] = ACTIONS(7),
    [anon_sym_LBRACE] = ACTIONS(11),
    [anon_sym_if] = ACTIONS(25),
    [anon_sym_print] = ACTIONS(15),
    [anon_sym_DASH] = ACTIONS(27),
    [anon_sym_BANG] = ACTIONS(29),
    [anon_sym_SLASH] = ACTIONS(31),
    [anon_sym_STAR] = ACTIONS(33),
    [anon_sym_PLUS] = ACTIONS(35),
    [anon_sym_DOT] = ACTIONS(37),
    [anon_sym_LT] = ACTIONS(39),
    [anon_sym_LT_EQ] = ACTIONS(41),
    [anon_sym_GT_EQ] = ACTIONS(41),
    [anon_sym_GT] = ACTIONS(39),
    [anon_sym_BANG_EQ] = ACTIONS(43),
    [anon_sym_EQ_EQ] = ACTIONS(43),
    [anon_sym_and] = ACTIONS(45),
    [anon_sym_or] = ACTIONS(47),
    [sym_number] = ACTIONS(19),
    [sym_string] = ACTIONS(19),
    [anon_sym_true] = ACTIONS(21),
    [anon_sym_false] = ACTIONS(21),
    [sym_null] = ACTIONS(23),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
  [3] = {
    [sym__statement] = STATE(53),
    [sym_block] = STATE(64),
    [sym_ifStatement] = STATE(64),
    [sym_expressionStatement] = STATE(64),
    [sym_printStatement] = STATE(64),
    [sym__expression] = STATE(66),
    [sym_unary] = STATE(17),
    [sym_binary] = STATE(17),
    [sym_comparison] = STATE(17),
    [sym_equality] = STATE(17),
    [sym_logical] = STATE(17),
    [sym_assignment] = STATE(17),
    [sym__primary] = STATE(17),
    [sym_bool] = STATE(23),
    [sym_comment] = STATE(3),
    [sym_identifier] = ACTIONS(7),
    [anon_sym_LBRACE] = ACTIONS(49),
    [anon_sym_if] = ACTIONS(51),
    [anon_sym_print] = ACTIONS(53),
    [anon_sym_DASH] = ACTIONS(27),
    [anon_sym_BANG] = ACTIONS(29),
    [anon_sym_SLASH] = ACTIONS(31),
    [anon_sym_STAR] = ACTIONS(33),
    [anon_sym_PLUS] = ACTIONS(35),
    [anon_sym_DOT] = ACTIONS(37),
    [anon_sym_LT] = ACTIONS(39),
    [anon_sym_LT_EQ] = ACTIONS(41),
    [anon_sym_GT_EQ] = ACTIONS(41),
    [anon_sym_GT] = ACTIONS(39),
    [anon_sym_BANG_EQ] = ACTIONS(43),
    [anon_sym_EQ_EQ] = ACTIONS(43),
    [anon_sym_and] = ACTIONS(45),
    [anon_sym_or] = ACTIONS(47),
    [sym_number] = ACTIONS(19),
    [sym_string] = ACTIONS(19),
    [anon_sym_true] = ACTIONS(21),
    [anon_sym_false] = ACTIONS(21),
    [sym_null] = ACTIONS(23),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
  [4] = {
    [sym__statement] = STATE(56),
    [sym_block] = STATE(58),
    [sym_ifStatement] = STATE(58),
    [sym_expressionStatement] = STATE(58),
    [sym_printStatement] = STATE(58),
    [sym__expression] = STATE(82),
    [sym_unary] = STATE(17),
    [sym_binary] = STATE(17),
    [sym_comparison] = STATE(17),
    [sym_equality] = STATE(17),
    [sym_logical] = STATE(17),
    [sym_assignment] = STATE(17),
    [sym__primary] = STATE(17),
    [sym_bool] = STATE(23),
    [sym_comment] = STATE(4),
    [sym_identifier] = ACTIONS(7),
    [anon_sym_LBRACE] = ACTIONS(11),
    [anon_sym_if] = ACTIONS(25),
    [anon_sym_print] = ACTIONS(15),
    [anon_sym_DASH] = ACTIONS(27),
    [anon_sym_BANG] = ACTIONS(29),
    [anon_sym_SLASH] = ACTIONS(31),
    [anon_sym_STAR] = ACTIONS(33),
    [anon_sym_PLUS] = ACTIONS(35),
    [anon_sym_DOT] = ACTIONS(37),
    [anon_sym_LT] = ACTIONS(39),
    [anon_sym_LT_EQ] = ACTIONS(41),
    [anon_sym_GT_EQ] = ACTIONS(41),
    [anon_sym_GT] = ACTIONS(39),
    [anon_sym_BANG_EQ] = ACTIONS(43),
    [anon_sym_EQ_EQ] = ACTIONS(43),
    [anon_sym_and] = ACTIONS(45),
    [anon_sym_or] = ACTIONS(47),
    [sym_number] = ACTIONS(19),
    [sym_string] = ACTIONS(19),
    [anon_sym_true] = ACTIONS(21),
    [anon_sym_false] = ACTIONS(21),
    [sym_null] = ACTIONS(23),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
  [5] = {
    [sym__statement] = STATE(49),
    [sym_block] = STATE(64),
    [sym_ifStatement] = STATE(64),
    [sym_expressionStatement] = STATE(64),
    [sym_printStatement] = STATE(64),
    [sym__expression] = STATE(66),
    [sym_unary] = STATE(17),
    [sym_binary] = STATE(17),
    [sym_comparison] = STATE(17),
    [sym_equality] = STATE(17),
    [sym_logical] = STATE(17),
    [sym_assignment] = STATE(17),
    [sym__primary] = STATE(17),
    [sym_bool] = STATE(23),
    [sym_comment] = STATE(5),
    [sym_identifier] = ACTIONS(7),
    [anon_sym_LBRACE] = ACTIONS(49),
    [anon_sym_if] = ACTIONS(51),
    [anon_sym_print] = ACTIONS(53),
    [anon_sym_DASH] = ACTIONS(27),
    [anon_sym_BANG] = ACTIONS(29),
    [anon_sym_SLASH] = ACTIONS(31),
    [anon_sym_STAR] = ACTIONS(33),
    [anon_sym_PLUS] = ACTIONS(35),
    [anon_sym_DOT] = ACTIONS(37),
    [anon_sym_LT] = ACTIONS(39),
    [anon_sym_LT_EQ] = ACTIONS(41),
    [anon_sym_GT_EQ] = ACTIONS(41),
    [anon_sym_GT] = ACTIONS(39),
    [anon_sym_BANG_EQ] = ACTIONS(43),
    [anon_sym_EQ_EQ] = ACTIONS(43),
    [anon_sym_and] = ACTIONS(45),
    [anon_sym_or] = ACTIONS(47),
    [sym_number] = ACTIONS(19),
    [sym_string] = ACTIONS(19),
    [anon_sym_true] = ACTIONS(21),
    [anon_sym_false] = ACTIONS(21),
    [sym_null] = ACTIONS(23),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
  [6] = {
    [sym__declaration] = STATE(78),
    [sym_varDeclaration] = STATE(83),
    [sym__statement] = STATE(83),
    [sym_block] = STATE(64),
    [sym_ifStatement] = STATE(64),
    [sym_expressionStatement] = STATE(64),
    [sym_printStatement] = STATE(64),
    [sym__expression] = STATE(66),
    [sym_unary] = STATE(17),
    [sym_binary] = STATE(17),
    [sym_comparison] = STATE(17),
    [sym_equality] = STATE(17),
    [sym_logical] = STATE(17),
    [sym_assignment] = STATE(17),
    [sym__primary] = STATE(17),
    [sym_bool] = STATE(23),
    [sym_comment] = STATE(6),
    [aux_sym_source_file_repeat1] = STATE(10),
    [sym_identifier] = ACTIONS(7),
    [anon_sym_var] = ACTIONS(55),
    [anon_sym_const] = ACTIONS(55),
    [anon_sym_LBRACE] = ACTIONS(49),
    [anon_sym_RBRACE] = ACTIONS(57),
    [anon_sym_if] = ACTIONS(59),
    [anon_sym_print] = ACTIONS(53),
    [anon_sym_DASH] = ACTIONS(17),
    [anon_sym_BANG] = ACTIONS(17),
    [sym_number] = ACTIONS(19),
    [sym_string] = ACTIONS(19),
    [anon_sym_true] = ACTIONS(21),
    [anon_sym_false] = ACTIONS(21),
    [sym_null] = ACTIONS(23),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
  [7] = {
    [sym__declaration] = STATE(78),
    [sym_varDeclaration] = STATE(83),
    [sym__statement] = STATE(83),
    [sym_block] = STATE(64),
    [sym_ifStatement] = STATE(64),
    [sym_expressionStatement] = STATE(64),
    [sym_printStatement] = STATE(64),
    [sym__expression] = STATE(66),
    [sym_unary] = STATE(17),
    [sym_binary] = STATE(17),
    [sym_comparison] = STATE(17),
    [sym_equality] = STATE(17),
    [sym_logical] = STATE(17),
    [sym_assignment] = STATE(17),
    [sym__primary] = STATE(17),
    [sym_bool] = STATE(23),
    [sym_comment] = STATE(7),
    [aux_sym_source_file_repeat1] = STATE(6),
    [sym_identifier] = ACTIONS(7),
    [anon_sym_var] = ACTIONS(55),
    [anon_sym_const] = ACTIONS(55),
    [anon_sym_LBRACE] = ACTIONS(49),
    [anon_sym_RBRACE] = ACTIONS(61),
    [anon_sym_if] = ACTIONS(59),
    [anon_sym_print] = ACTIONS(53),
    [anon_sym_DASH] = ACTIONS(17),
    [anon_sym_BANG] = ACTIONS(17),
    [sym_number] = ACTIONS(19),
    [sym_string] = ACTIONS(19),
    [anon_sym_true] = ACTIONS(21),
    [anon_sym_false] = ACTIONS(21),
    [sym_null] = ACTIONS(23),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
  [8] = {
    [sym__declaration] = STATE(75),
    [sym_varDeclaration] = STATE(76),
    [sym__statement] = STATE(76),
    [sym_block] = STATE(58),
    [sym_ifStatement] = STATE(58),
    [sym_expressionStatement] = STATE(58),
    [sym_printStatement] = STATE(58),
    [sym__expression] = STATE(82),
    [sym_unary] = STATE(17),
    [sym_binary] = STATE(17),
    [sym_comparison] = STATE(17),
    [sym_equality] = STATE(17),
    [sym_logical] = STATE(17),
    [sym_assignment] = STATE(17),
    [sym__primary] = STATE(17),
    [sym_bool] = STATE(23),
    [sym_comment] = STATE(8),
    [aux_sym_source_file_repeat1] = STATE(8),
    [ts_builtin_sym_end] = ACTIONS(63),
    [sym_identifier] = ACTIONS(65),
    [anon_sym_var] = ACTIONS(68),
    [anon_sym_const] = ACTIONS(68),
    [anon_sym_LBRACE] = ACTIONS(71),
    [anon_sym_if] = ACTIONS(74),
    [anon_sym_print] = ACTIONS(77),
    [anon_sym_DASH] = ACTIONS(80),
    [anon_sym_BANG] = ACTIONS(80),
    [sym_number] = ACTIONS(83),
    [sym_string] = ACTIONS(83),
    [anon_sym_true] = ACTIONS(86),
    [anon_sym_false] = ACTIONS(86),
    [sym_null] = ACTIONS(89),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
  [9] = {
    [sym__declaration] = STATE(75),
    [sym_varDeclaration] = STATE(76),
    [sym__statement] = STATE(76),
    [sym_block] = STATE(58),
    [sym_ifStatement] = STATE(58),
    [sym_expressionStatement] = STATE(58),
    [sym_printStatement] = STATE(58),
    [sym__expression] = STATE(82),
    [sym_unary] = STATE(17),
    [sym_binary] = STATE(17),
    [sym_comparison] = STATE(17),
    [sym_equality] = STATE(17),
    [sym_logical] = STATE(17),
    [sym_assignment] = STATE(17),
    [sym__primary] = STATE(17),
    [sym_bool] = STATE(23),
    [sym_comment] = STATE(9),
    [aux_sym_source_file_repeat1] = STATE(8),
    [ts_builtin_sym_end] = ACTIONS(92),
    [sym_identifier] = ACTIONS(7),
    [anon_sym_var] = ACTIONS(9),
    [anon_sym_const] = ACTIONS(9),
    [anon_sym_LBRACE] = ACTIONS(11),
    [anon_sym_if] = ACTIONS(13),
    [anon_sym_print] = ACTIONS(15),
    [anon_sym_DASH] = ACTIONS(17),
    [anon_sym_BANG] = ACTIONS(17),
    [sym_number] = ACTIONS(19),
    [sym_string] = ACTIONS(19),
    [anon_sym_true] = ACTIONS(21),
    [anon_sym_false] = ACTIONS(21),
    [sym_null] = ACTIONS(23),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
  [10] = {
    [sym__declaration] = STATE(78),
    [sym_varDeclaration] = STATE(83),
    [sym__statement] = STATE(83),
    [sym_block] = STATE(64),
    [sym_ifStatement] = STATE(64),
    [sym_expressionStatement] = STATE(64),
    [sym_printStatement] = STATE(64),
    [sym__expression] = STATE(66),
    [sym_unary] = STATE(17),
    [sym_binary] = STATE(17),
    [sym_comparison] = STATE(17),
    [sym_equality] = STATE(17),
    [sym_logical] = STATE(17),
    [sym_assignment] = STATE(17),
    [sym__primary] = STATE(17),
    [sym_bool] = STATE(23),
    [sym_comment] = STATE(10),
    [aux_sym_source_file_repeat1] = STATE(10),
    [sym_identifier] = ACTIONS(65),
    [anon_sym_var] = ACTIONS(94),
    [anon_sym_const] = ACTIONS(94),
    [anon_sym_LBRACE] = ACTIONS(97),
    [anon_sym_RBRACE] = ACTIONS(63),
    [anon_sym_if] = ACTIONS(100),
    [anon_sym_print] = ACTIONS(103),
    [anon_sym_DASH] = ACTIONS(80),
    [anon_sym_BANG] = ACTIONS(80),
    [sym_number] = ACTIONS(83),
    [sym_string] = ACTIONS(83),
    [anon_sym_true] = ACTIONS(86),
    [anon_sym_false] = ACTIONS(86),
    [sym_null] = ACTIONS(89),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
  [11] = {
    [sym__declaration] = STATE(78),
    [sym_varDeclaration] = STATE(83),
    [sym__statement] = STATE(83),
    [sym_block] = STATE(64),
    [sym_ifStatement] = STATE(64),
    [sym_expressionStatement] = STATE(64),
    [sym_printStatement] = STATE(64),
    [sym__expression] = STATE(66),
    [sym_unary] = STATE(17),
    [sym_binary] = STATE(17),
    [sym_comparison] = STATE(17),
    [sym_equality] = STATE(17),
    [sym_logical] = STATE(17),
    [sym_assignment] = STATE(17),
    [sym__primary] = STATE(17),
    [sym_bool] = STATE(23),
    [sym_comment] = STATE(11),
    [aux_sym_source_file_repeat1] = STATE(10),
    [sym_identifier] = ACTIONS(7),
    [anon_sym_var] = ACTIONS(55),
    [anon_sym_const] = ACTIONS(55),
    [anon_sym_LBRACE] = ACTIONS(49),
    [anon_sym_RBRACE] = ACTIONS(106),
    [anon_sym_if] = ACTIONS(59),
    [anon_sym_print] = ACTIONS(53),
    [anon_sym_DASH] = ACTIONS(17),
    [anon_sym_BANG] = ACTIONS(17),
    [sym_number] = ACTIONS(19),
    [sym_string] = ACTIONS(19),
    [anon_sym_true] = ACTIONS(21),
    [anon_sym_false] = ACTIONS(21),
    [sym_null] = ACTIONS(23),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
  [12] = {
    [sym__declaration] = STATE(78),
    [sym_varDeclaration] = STATE(83),
    [sym__statement] = STATE(83),
    [sym_block] = STATE(64),
    [sym_ifStatement] = STATE(64),
    [sym_expressionStatement] = STATE(64),
    [sym_printStatement] = STATE(64),
    [sym__expression] = STATE(66),
    [sym_unary] = STATE(17),
    [sym_binary] = STATE(17),
    [sym_comparison] = STATE(17),
    [sym_equality] = STATE(17),
    [sym_logical] = STATE(17),
    [sym_assignment] = STATE(17),
    [sym__primary] = STATE(17),
    [sym_bool] = STATE(23),
    [sym_comment] = STATE(12),
    [aux_sym_source_file_repeat1] = STATE(11),
    [sym_identifier] = ACTIONS(7),
    [anon_sym_var] = ACTIONS(55),
    [anon_sym_const] = ACTIONS(55),
    [anon_sym_LBRACE] = ACTIONS(49),
    [anon_sym_RBRACE] = ACTIONS(108),
    [anon_sym_if] = ACTIONS(59),
    [anon_sym_print] = ACTIONS(53),
    [anon_sym_DASH] = ACTIONS(17),
    [anon_sym_BANG] = ACTIONS(17),
    [sym_number] = ACTIONS(19),
    [sym_string] = ACTIONS(19),
    [anon_sym_true] = ACTIONS(21),
    [anon_sym_false] = ACTIONS(21),
    [sym_null] = ACTIONS(23),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
  [13] = {
    [sym_comment] = STATE(13),
    [sym_identifier] = ACTIONS(110),
    [anon_sym_EQ] = ACTIONS(112),
    [anon_sym_SEMI] = ACTIONS(114),
    [anon_sym_LBRACE] = ACTIONS(114),
    [anon_sym_if] = ACTIONS(110),
    [anon_sym_print] = ACTIONS(110),
    [anon_sym_DASH] = ACTIONS(114),
    [anon_sym_BANG] = ACTIONS(110),
    [anon_sym_SLASH] = ACTIONS(110),
    [anon_sym_STAR] = ACTIONS(114),
    [anon_sym_PLUS] = ACTIONS(114),
    [anon_sym_DOT] = ACTIONS(114),
    [anon_sym_LT] = ACTIONS(110),
    [anon_sym_LT_EQ] = ACTIONS(114),
    [anon_sym_GT_EQ] = ACTIONS(114),
    [anon_sym_GT] = ACTIONS(110),
    [anon_sym_BANG_EQ] = ACTIONS(114),
    [anon_sym_EQ_EQ] = ACTIONS(114),
    [anon_sym_and] = ACTIONS(110),
    [anon_sym_or] = ACTIONS(110),
    [sym_number] = ACTIONS(114),
    [sym_string] = ACTIONS(114),
    [anon_sym_true] = ACTIONS(110),
    [anon_sym_false] = ACTIONS(110),
    [sym_null] = ACTIONS(110),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
  [14] = {
    [sym__statement] = STATE(63),
    [sym_block] = STATE(58),
    [sym_ifStatement] = STATE(58),
    [sym_expressionStatement] = STATE(58),
    [sym_printStatement] = STATE(58),
    [sym__expression] = STATE(82),
    [sym_unary] = STATE(17),
    [sym_binary] = STATE(17),
    [sym_comparison] = STATE(17),
    [sym_equality] = STATE(17),
    [sym_logical] = STATE(17),
    [sym_assignment] = STATE(17),
    [sym__primary] = STATE(17),
    [sym_bool] = STATE(23),
    [sym_comment] = STATE(14),
    [sym_identifier] = ACTIONS(7),
    [anon_sym_LBRACE] = ACTIONS(11),
    [anon_sym_if] = ACTIONS(13),
    [anon_sym_print] = ACTIONS(15),
    [anon_sym_DASH] = ACTIONS(17),
    [anon_sym_BANG] = ACTIONS(17),
    [sym_number] = ACTIONS(19),
    [sym_string] = ACTIONS(19),
    [anon_sym_true] = ACTIONS(21),
    [anon_sym_false] = ACTIONS(21),
    [sym_null] = ACTIONS(23),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
  [15] = {
    [sym__statement] = STATE(55),
    [sym_block] = STATE(64),
    [sym_ifStatement] = STATE(64),
    [sym_expressionStatement] = STATE(64),
    [sym_printStatement] = STATE(64),
    [sym__expression] = STATE(66),
    [sym_unary] = STATE(17),
    [sym_binary] = STATE(17),
    [sym_comparison] = STATE(17),
    [sym_equality] = STATE(17),
    [sym_logical] = STATE(17),
    [sym_assignment] = STATE(17),
    [sym__primary] = STATE(17),
    [sym_bool] = STATE(23),
    [sym_comment] = STATE(15),
    [sym_identifier] = ACTIONS(7),
    [anon_sym_LBRACE] = ACTIONS(49),
    [anon_sym_if] = ACTIONS(59),
    [anon_sym_print] = ACTIONS(53),
    [anon_sym_DASH] = ACTIONS(17),
    [anon_sym_BANG] = ACTIONS(17),
    [sym_number] = ACTIONS(19),
    [sym_string] = ACTIONS(19),
    [anon_sym_true] = ACTIONS(21),
    [anon_sym_false] = ACTIONS(21),
    [sym_null] = ACTIONS(23),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 9,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(31), 1,
      anon_sym_SLASH,
    ACTIONS(33), 1,
      anon_sym_STAR,
    STATE(16), 1,
      sym_comment,
    ACTIONS(35), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(39), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(41), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(118), 7,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_DOT,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      sym_number,
      sym_string,
    ACTIONS(116), 9,
      anon_sym_if,
      anon_sym_print,
      anon_sym_BANG,
      anon_sym_and,
      anon_sym_or,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_identifier,
  [45] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(17), 1,
      sym_comment,
    ACTIONS(120), 12,
      anon_sym_if,
      anon_sym_print,
      anon_sym_BANG,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_and,
      anon_sym_or,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_identifier,
    ACTIONS(122), 12,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DOT,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      sym_number,
      sym_string,
  [80] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(18), 1,
      sym_comment,
    ACTIONS(124), 12,
      anon_sym_if,
      anon_sym_print,
      anon_sym_BANG,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_and,
      anon_sym_or,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_identifier,
    ACTIONS(126), 12,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DOT,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      sym_number,
      sym_string,
  [115] = 13,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(31), 1,
      anon_sym_SLASH,
    ACTIONS(33), 1,
      anon_sym_STAR,
    ACTIONS(37), 1,
      anon_sym_DOT,
    ACTIONS(45), 1,
      anon_sym_and,
    ACTIONS(47), 1,
      anon_sym_or,
    STATE(19), 1,
      sym_comment,
    ACTIONS(35), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(39), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(41), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(43), 2,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
    ACTIONS(130), 4,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      sym_number,
      sym_string,
    ACTIONS(128), 7,
      anon_sym_if,
      anon_sym_print,
      anon_sym_BANG,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_identifier,
  [168] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(31), 1,
      anon_sym_SLASH,
    ACTIONS(33), 1,
      anon_sym_STAR,
    STATE(20), 1,
      sym_comment,
    ACTIONS(132), 11,
      anon_sym_if,
      anon_sym_print,
      anon_sym_BANG,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_and,
      anon_sym_or,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_identifier,
    ACTIONS(134), 11,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_DOT,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      sym_number,
      sym_string,
  [207] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(21), 1,
      sym_comment,
    ACTIONS(132), 12,
      anon_sym_if,
      anon_sym_print,
      anon_sym_BANG,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_and,
      anon_sym_or,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_identifier,
    ACTIONS(134), 12,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DOT,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      sym_number,
      sym_string,
  [242] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(31), 1,
      anon_sym_SLASH,
    ACTIONS(33), 1,
      anon_sym_STAR,
    ACTIONS(45), 1,
      anon_sym_and,
    ACTIONS(47), 1,
      anon_sym_or,
    STATE(22), 1,
      sym_comment,
    ACTIONS(35), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(39), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(41), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(43), 2,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
    ACTIONS(134), 5,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_DOT,
      sym_number,
      sym_string,
    ACTIONS(132), 7,
      anon_sym_if,
      anon_sym_print,
      anon_sym_BANG,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_identifier,
  [293] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(23), 1,
      sym_comment,
    ACTIONS(110), 12,
      anon_sym_if,
      anon_sym_print,
      anon_sym_BANG,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_and,
      anon_sym_or,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_identifier,
    ACTIONS(114), 12,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DOT,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      sym_number,
      sym_string,
  [328] = 10,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(31), 1,
      anon_sym_SLASH,
    ACTIONS(33), 1,
      anon_sym_STAR,
    STATE(24), 1,
      sym_comment,
    ACTIONS(35), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(39), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(41), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(43), 2,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
    ACTIONS(138), 5,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_DOT,
      sym_number,
      sym_string,
    ACTIONS(136), 9,
      anon_sym_if,
      anon_sym_print,
      anon_sym_BANG,
      anon_sym_and,
      anon_sym_or,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_identifier,
  [375] = 11,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(31), 1,
      anon_sym_SLASH,
    ACTIONS(33), 1,
      anon_sym_STAR,
    ACTIONS(45), 1,
      anon_sym_and,
    STATE(25), 1,
      sym_comment,
    ACTIONS(35), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(39), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(41), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(43), 2,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
    ACTIONS(138), 5,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_DOT,
      sym_number,
      sym_string,
    ACTIONS(136), 8,
      anon_sym_if,
      anon_sym_print,
      anon_sym_BANG,
      anon_sym_or,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_identifier,
  [424] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(26), 1,
      sym_comment,
    ACTIONS(134), 3,
      anon_sym_LBRACE,
      sym_number,
      sym_string,
    ACTIONS(124), 5,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_and,
      anon_sym_or,
    ACTIONS(132), 7,
      anon_sym_if,
      anon_sym_print,
      anon_sym_BANG,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_identifier,
    ACTIONS(126), 9,
      anon_sym_SEMI,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DOT,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
  [463] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(27), 1,
      sym_comment,
    ACTIONS(140), 12,
      anon_sym_if,
      anon_sym_print,
      anon_sym_BANG,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_and,
      anon_sym_or,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_identifier,
    ACTIONS(142), 12,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DOT,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      sym_number,
      sym_string,
  [498] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(31), 1,
      anon_sym_SLASH,
    ACTIONS(33), 1,
      anon_sym_STAR,
    STATE(28), 1,
      sym_comment,
    ACTIONS(35), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(146), 9,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_DOT,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      sym_number,
      sym_string,
    ACTIONS(144), 11,
      anon_sym_if,
      anon_sym_print,
      anon_sym_BANG,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_and,
      anon_sym_or,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_identifier,
  [539] = 10,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(23), 1,
      sym_null,
    STATE(23), 1,
      sym_bool,
    STATE(25), 1,
      sym__expression,
    STATE(29), 1,
      sym_comment,
    ACTIONS(17), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(19), 2,
      sym_number,
      sym_string,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(17), 7,
      sym_unary,
      sym_binary,
      sym_comparison,
      sym_equality,
      sym_logical,
      sym_assignment,
      sym__primary,
  [579] = 10,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(23), 1,
      sym_null,
    STATE(18), 1,
      sym__expression,
    STATE(23), 1,
      sym_bool,
    STATE(30), 1,
      sym_comment,
    ACTIONS(17), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(19), 2,
      sym_number,
      sym_string,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(17), 7,
      sym_unary,
      sym_binary,
      sym_comparison,
      sym_equality,
      sym_logical,
      sym_assignment,
      sym__primary,
  [619] = 10,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(23), 1,
      sym_null,
    STATE(23), 1,
      sym_bool,
    STATE(31), 1,
      sym_comment,
    STATE(84), 1,
      sym__expression,
    ACTIONS(17), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(19), 2,
      sym_number,
      sym_string,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(17), 7,
      sym_unary,
      sym_binary,
      sym_comparison,
      sym_equality,
      sym_logical,
      sym_assignment,
      sym__primary,
  [659] = 10,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(23), 1,
      sym_null,
    STATE(23), 1,
      sym_bool,
    STATE(26), 1,
      sym__expression,
    STATE(32), 1,
      sym_comment,
    ACTIONS(17), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(19), 2,
      sym_number,
      sym_string,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(17), 7,
      sym_unary,
      sym_binary,
      sym_comparison,
      sym_equality,
      sym_logical,
      sym_assignment,
      sym__primary,
  [699] = 10,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(23), 1,
      sym_null,
    STATE(23), 1,
      sym_bool,
    STATE(33), 1,
      sym_comment,
    STATE(80), 1,
      sym__expression,
    ACTIONS(17), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(19), 2,
      sym_number,
      sym_string,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(17), 7,
      sym_unary,
      sym_binary,
      sym_comparison,
      sym_equality,
      sym_logical,
      sym_assignment,
      sym__primary,
  [739] = 10,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(23), 1,
      sym_null,
    STATE(2), 1,
      sym__expression,
    STATE(23), 1,
      sym_bool,
    STATE(34), 1,
      sym_comment,
    ACTIONS(17), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(19), 2,
      sym_number,
      sym_string,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(17), 7,
      sym_unary,
      sym_binary,
      sym_comparison,
      sym_equality,
      sym_logical,
      sym_assignment,
      sym__primary,
  [779] = 10,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(23), 1,
      sym_null,
    STATE(19), 1,
      sym__expression,
    STATE(23), 1,
      sym_bool,
    STATE(35), 1,
      sym_comment,
    ACTIONS(17), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(19), 2,
      sym_number,
      sym_string,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(17), 7,
      sym_unary,
      sym_binary,
      sym_comparison,
      sym_equality,
      sym_logical,
      sym_assignment,
      sym__primary,
  [819] = 10,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(23), 1,
      sym_null,
    STATE(5), 1,
      sym__expression,
    STATE(23), 1,
      sym_bool,
    STATE(36), 1,
      sym_comment,
    ACTIONS(17), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(19), 2,
      sym_number,
      sym_string,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(17), 7,
      sym_unary,
      sym_binary,
      sym_comparison,
      sym_equality,
      sym_logical,
      sym_assignment,
      sym__primary,
  [859] = 10,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(23), 1,
      sym_null,
    STATE(20), 1,
      sym__expression,
    STATE(23), 1,
      sym_bool,
    STATE(37), 1,
      sym_comment,
    ACTIONS(17), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(19), 2,
      sym_number,
      sym_string,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(17), 7,
      sym_unary,
      sym_binary,
      sym_comparison,
      sym_equality,
      sym_logical,
      sym_assignment,
      sym__primary,
  [899] = 10,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(23), 1,
      sym_null,
    STATE(21), 1,
      sym__expression,
    STATE(23), 1,
      sym_bool,
    STATE(38), 1,
      sym_comment,
    ACTIONS(17), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(19), 2,
      sym_number,
      sym_string,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(17), 7,
      sym_unary,
      sym_binary,
      sym_comparison,
      sym_equality,
      sym_logical,
      sym_assignment,
      sym__primary,
  [939] = 10,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(23), 1,
      sym_null,
    STATE(22), 1,
      sym__expression,
    STATE(23), 1,
      sym_bool,
    STATE(39), 1,
      sym_comment,
    ACTIONS(17), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(19), 2,
      sym_number,
      sym_string,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(17), 7,
      sym_unary,
      sym_binary,
      sym_comparison,
      sym_equality,
      sym_logical,
      sym_assignment,
      sym__primary,
  [979] = 10,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(23), 1,
      sym_null,
    STATE(23), 1,
      sym_bool,
    STATE(40), 1,
      sym_comment,
    STATE(72), 1,
      sym__expression,
    ACTIONS(17), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(19), 2,
      sym_number,
      sym_string,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(17), 7,
      sym_unary,
      sym_binary,
      sym_comparison,
      sym_equality,
      sym_logical,
      sym_assignment,
      sym__primary,
  [1019] = 10,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(23), 1,
      sym_null,
    STATE(23), 1,
      sym_bool,
    STATE(28), 1,
      sym__expression,
    STATE(41), 1,
      sym_comment,
    ACTIONS(17), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(19), 2,
      sym_number,
      sym_string,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(17), 7,
      sym_unary,
      sym_binary,
      sym_comparison,
      sym_equality,
      sym_logical,
      sym_assignment,
      sym__primary,
  [1059] = 10,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(23), 1,
      sym_null,
    STATE(16), 1,
      sym__expression,
    STATE(23), 1,
      sym_bool,
    STATE(42), 1,
      sym_comment,
    ACTIONS(17), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(19), 2,
      sym_number,
      sym_string,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(17), 7,
      sym_unary,
      sym_binary,
      sym_comparison,
      sym_equality,
      sym_logical,
      sym_assignment,
      sym__primary,
  [1099] = 10,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(23), 1,
      sym_null,
    STATE(23), 1,
      sym_bool,
    STATE(24), 1,
      sym__expression,
    STATE(43), 1,
      sym_comment,
    ACTIONS(17), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(19), 2,
      sym_number,
      sym_string,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(17), 7,
      sym_unary,
      sym_binary,
      sym_comparison,
      sym_equality,
      sym_logical,
      sym_assignment,
      sym__primary,
  [1139] = 10,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(23), 1,
      sym_null,
    STATE(3), 1,
      sym__expression,
    STATE(23), 1,
      sym_bool,
    STATE(44), 1,
      sym_comment,
    ACTIONS(17), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(19), 2,
      sym_number,
      sym_string,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(17), 7,
      sym_unary,
      sym_binary,
      sym_comparison,
      sym_equality,
      sym_logical,
      sym_assignment,
      sym__primary,
  [1179] = 10,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(23), 1,
      sym_null,
    STATE(23), 1,
      sym_bool,
    STATE(45), 1,
      sym_comment,
    STATE(77), 1,
      sym__expression,
    ACTIONS(17), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(19), 2,
      sym_number,
      sym_string,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(17), 7,
      sym_unary,
      sym_binary,
      sym_comparison,
      sym_equality,
      sym_logical,
      sym_assignment,
      sym__primary,
  [1219] = 10,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(23), 1,
      sym_null,
    STATE(23), 1,
      sym_bool,
    STATE(46), 1,
      sym_comment,
    STATE(65), 1,
      sym__expression,
    ACTIONS(17), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(19), 2,
      sym_number,
      sym_string,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(17), 7,
      sym_unary,
      sym_binary,
      sym_comparison,
      sym_equality,
      sym_logical,
      sym_assignment,
      sym__primary,
  [1259] = 10,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(23), 1,
      sym_null,
    STATE(23), 1,
      sym_bool,
    STATE(47), 1,
      sym_comment,
    STATE(81), 1,
      sym__expression,
    ACTIONS(17), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(19), 2,
      sym_number,
      sym_string,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(17), 7,
      sym_unary,
      sym_binary,
      sym_comparison,
      sym_equality,
      sym_logical,
      sym_assignment,
      sym__primary,
  [1299] = 10,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(23), 1,
      sym_null,
    STATE(4), 1,
      sym__expression,
    STATE(23), 1,
      sym_bool,
    STATE(48), 1,
      sym_comment,
    ACTIONS(17), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(19), 2,
      sym_number,
      sym_string,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(17), 7,
      sym_unary,
      sym_binary,
      sym_comparison,
      sym_equality,
      sym_logical,
      sym_assignment,
      sym__primary,
  [1339] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(49), 1,
      sym_comment,
    ACTIONS(150), 6,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
      sym_string,
    ACTIONS(148), 9,
      anon_sym_var,
      anon_sym_const,
      anon_sym_if,
      anon_sym_else,
      anon_sym_print,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_identifier,
  [1365] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(50), 1,
      sym_comment,
    ACTIONS(154), 6,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
      sym_string,
    ACTIONS(152), 9,
      anon_sym_var,
      anon_sym_const,
      anon_sym_if,
      anon_sym_else,
      anon_sym_print,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_identifier,
  [1391] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(51), 1,
      sym_comment,
    ACTIONS(158), 6,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
      sym_string,
    ACTIONS(156), 9,
      anon_sym_var,
      anon_sym_const,
      anon_sym_if,
      anon_sym_else,
      anon_sym_print,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_identifier,
  [1417] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(52), 1,
      sym_comment,
    ACTIONS(162), 6,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
      sym_string,
    ACTIONS(160), 9,
      anon_sym_var,
      anon_sym_const,
      anon_sym_if,
      anon_sym_else,
      anon_sym_print,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_identifier,
  [1443] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(164), 1,
      anon_sym_else,
    STATE(53), 1,
      sym_comment,
    ACTIONS(150), 6,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
      sym_string,
    ACTIONS(148), 8,
      anon_sym_var,
      anon_sym_const,
      anon_sym_if,
      anon_sym_print,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_identifier,
  [1471] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(54), 1,
      sym_comment,
    ACTIONS(168), 6,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
      sym_string,
    ACTIONS(166), 9,
      anon_sym_var,
      anon_sym_const,
      anon_sym_if,
      anon_sym_else,
      anon_sym_print,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_identifier,
  [1497] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(55), 1,
      sym_comment,
    ACTIONS(172), 6,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
      sym_string,
    ACTIONS(170), 9,
      anon_sym_var,
      anon_sym_const,
      anon_sym_if,
      anon_sym_else,
      anon_sym_print,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_identifier,
  [1523] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(56), 1,
      sym_comment,
    ACTIONS(150), 6,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
      sym_string,
    ACTIONS(148), 9,
      anon_sym_var,
      anon_sym_const,
      anon_sym_if,
      anon_sym_else,
      anon_sym_print,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_identifier,
  [1549] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(57), 1,
      sym_comment,
    ACTIONS(154), 6,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
      sym_string,
    ACTIONS(152), 9,
      anon_sym_var,
      anon_sym_const,
      anon_sym_if,
      anon_sym_else,
      anon_sym_print,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_identifier,
  [1575] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(58), 1,
      sym_comment,
    ACTIONS(174), 6,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
      sym_string,
    ACTIONS(176), 9,
      anon_sym_var,
      anon_sym_const,
      anon_sym_if,
      anon_sym_else,
      anon_sym_print,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_identifier,
  [1601] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(59), 1,
      sym_comment,
    ACTIONS(158), 6,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
      sym_string,
    ACTIONS(156), 9,
      anon_sym_var,
      anon_sym_const,
      anon_sym_if,
      anon_sym_else,
      anon_sym_print,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_identifier,
  [1627] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(60), 1,
      sym_comment,
    ACTIONS(162), 6,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
      sym_string,
    ACTIONS(160), 9,
      anon_sym_var,
      anon_sym_const,
      anon_sym_if,
      anon_sym_else,
      anon_sym_print,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_identifier,
  [1653] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(178), 1,
      anon_sym_else,
    STATE(61), 1,
      sym_comment,
    ACTIONS(150), 6,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
      sym_string,
    ACTIONS(148), 8,
      anon_sym_var,
      anon_sym_const,
      anon_sym_if,
      anon_sym_print,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_identifier,
  [1681] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(62), 1,
      sym_comment,
    ACTIONS(168), 6,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
      sym_string,
    ACTIONS(166), 9,
      anon_sym_var,
      anon_sym_const,
      anon_sym_if,
      anon_sym_else,
      anon_sym_print,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_identifier,
  [1707] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(63), 1,
      sym_comment,
    ACTIONS(172), 6,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
      sym_string,
    ACTIONS(170), 9,
      anon_sym_var,
      anon_sym_const,
      anon_sym_if,
      anon_sym_else,
      anon_sym_print,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_identifier,
  [1733] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(64), 1,
      sym_comment,
    ACTIONS(174), 6,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
      sym_string,
    ACTIONS(176), 9,
      anon_sym_var,
      anon_sym_const,
      anon_sym_if,
      anon_sym_else,
      anon_sym_print,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_identifier,
  [1759] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(31), 1,
      anon_sym_SLASH,
    ACTIONS(33), 1,
      anon_sym_STAR,
    ACTIONS(37), 1,
      anon_sym_DOT,
    ACTIONS(180), 1,
      anon_sym_SEMI,
    ACTIONS(182), 1,
      anon_sym_and,
    ACTIONS(184), 1,
      anon_sym_or,
    STATE(65), 1,
      sym_comment,
    ACTIONS(35), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(39), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(41), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(43), 2,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
  [1800] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(31), 1,
      anon_sym_SLASH,
    ACTIONS(33), 1,
      anon_sym_STAR,
    ACTIONS(37), 1,
      anon_sym_DOT,
    ACTIONS(182), 1,
      anon_sym_and,
    ACTIONS(184), 1,
      anon_sym_or,
    ACTIONS(186), 1,
      anon_sym_SEMI,
    STATE(66), 1,
      sym_comment,
    ACTIONS(35), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(39), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(41), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(43), 2,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
  [1841] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(67), 1,
      sym_comment,
    ACTIONS(190), 6,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
      sym_string,
    ACTIONS(188), 8,
      anon_sym_var,
      anon_sym_const,
      anon_sym_if,
      anon_sym_print,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_identifier,
  [1866] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(68), 1,
      sym_comment,
    ACTIONS(190), 6,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
      sym_string,
    ACTIONS(188), 8,
      anon_sym_var,
      anon_sym_const,
      anon_sym_if,
      anon_sym_print,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_identifier,
  [1891] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(69), 1,
      sym_comment,
    ACTIONS(192), 6,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
      sym_string,
    ACTIONS(194), 8,
      anon_sym_var,
      anon_sym_const,
      anon_sym_if,
      anon_sym_print,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_identifier,
  [1916] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(70), 1,
      sym_comment,
    ACTIONS(198), 6,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
      sym_string,
    ACTIONS(196), 8,
      anon_sym_var,
      anon_sym_const,
      anon_sym_if,
      anon_sym_print,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_identifier,
  [1941] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(71), 1,
      sym_comment,
    ACTIONS(192), 6,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
      sym_string,
    ACTIONS(194), 8,
      anon_sym_var,
      anon_sym_const,
      anon_sym_if,
      anon_sym_print,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_identifier,
  [1966] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(31), 1,
      anon_sym_SLASH,
    ACTIONS(33), 1,
      anon_sym_STAR,
    ACTIONS(37), 1,
      anon_sym_DOT,
    ACTIONS(182), 1,
      anon_sym_and,
    ACTIONS(184), 1,
      anon_sym_or,
    ACTIONS(200), 1,
      anon_sym_SEMI,
    STATE(72), 1,
      sym_comment,
    ACTIONS(35), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(39), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(41), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(43), 2,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
  [2007] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(73), 1,
      sym_comment,
    ACTIONS(198), 6,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
      sym_string,
    ACTIONS(196), 8,
      anon_sym_var,
      anon_sym_const,
      anon_sym_if,
      anon_sym_print,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_identifier,
  [2032] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(74), 1,
      sym_comment,
    ACTIONS(204), 6,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
      sym_string,
    ACTIONS(202), 8,
      anon_sym_var,
      anon_sym_const,
      anon_sym_if,
      anon_sym_print,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_identifier,
  [2057] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(75), 1,
      sym_comment,
    ACTIONS(206), 6,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
      sym_string,
    ACTIONS(208), 8,
      anon_sym_var,
      anon_sym_const,
      anon_sym_if,
      anon_sym_print,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_identifier,
  [2082] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(76), 1,
      sym_comment,
    ACTIONS(210), 6,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
      sym_string,
    ACTIONS(212), 8,
      anon_sym_var,
      anon_sym_const,
      anon_sym_if,
      anon_sym_print,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_identifier,
  [2107] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(31), 1,
      anon_sym_SLASH,
    ACTIONS(33), 1,
      anon_sym_STAR,
    ACTIONS(37), 1,
      anon_sym_DOT,
    ACTIONS(182), 1,
      anon_sym_and,
    ACTIONS(184), 1,
      anon_sym_or,
    ACTIONS(214), 1,
      anon_sym_SEMI,
    STATE(77), 1,
      sym_comment,
    ACTIONS(35), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(39), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(41), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(43), 2,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
  [2148] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(78), 1,
      sym_comment,
    ACTIONS(206), 6,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
      sym_string,
    ACTIONS(208), 8,
      anon_sym_var,
      anon_sym_const,
      anon_sym_if,
      anon_sym_print,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_identifier,
  [2173] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(79), 1,
      sym_comment,
    ACTIONS(204), 6,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
      sym_string,
    ACTIONS(202), 8,
      anon_sym_var,
      anon_sym_const,
      anon_sym_if,
      anon_sym_print,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_identifier,
  [2198] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(31), 1,
      anon_sym_SLASH,
    ACTIONS(33), 1,
      anon_sym_STAR,
    ACTIONS(37), 1,
      anon_sym_DOT,
    ACTIONS(182), 1,
      anon_sym_and,
    ACTIONS(184), 1,
      anon_sym_or,
    ACTIONS(216), 1,
      anon_sym_SEMI,
    STATE(80), 1,
      sym_comment,
    ACTIONS(35), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(39), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(41), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(43), 2,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
  [2239] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(31), 1,
      anon_sym_SLASH,
    ACTIONS(33), 1,
      anon_sym_STAR,
    ACTIONS(37), 1,
      anon_sym_DOT,
    ACTIONS(182), 1,
      anon_sym_and,
    ACTIONS(184), 1,
      anon_sym_or,
    ACTIONS(218), 1,
      anon_sym_SEMI,
    STATE(81), 1,
      sym_comment,
    ACTIONS(35), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(39), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(41), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(43), 2,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
  [2280] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(31), 1,
      anon_sym_SLASH,
    ACTIONS(33), 1,
      anon_sym_STAR,
    ACTIONS(37), 1,
      anon_sym_DOT,
    ACTIONS(182), 1,
      anon_sym_and,
    ACTIONS(184), 1,
      anon_sym_or,
    ACTIONS(220), 1,
      anon_sym_SEMI,
    STATE(82), 1,
      sym_comment,
    ACTIONS(35), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(39), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(41), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(43), 2,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
  [2321] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(83), 1,
      sym_comment,
    ACTIONS(210), 6,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
      sym_string,
    ACTIONS(212), 8,
      anon_sym_var,
      anon_sym_const,
      anon_sym_if,
      anon_sym_print,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_identifier,
  [2346] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(31), 1,
      anon_sym_SLASH,
    ACTIONS(33), 1,
      anon_sym_STAR,
    ACTIONS(37), 1,
      anon_sym_DOT,
    ACTIONS(182), 1,
      anon_sym_and,
    ACTIONS(184), 1,
      anon_sym_or,
    ACTIONS(222), 1,
      anon_sym_SEMI,
    STATE(84), 1,
      sym_comment,
    ACTIONS(35), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(39), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(41), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(43), 2,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
  [2387] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(224), 1,
      anon_sym_EQ,
    ACTIONS(226), 1,
      anon_sym_SEMI,
    ACTIONS(228), 1,
      anon_sym_COLON,
    STATE(85), 1,
      sym_comment,
    STATE(88), 1,
      sym_typeHint,
  [2406] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(228), 1,
      anon_sym_COLON,
    ACTIONS(230), 1,
      anon_sym_EQ,
    ACTIONS(232), 1,
      anon_sym_SEMI,
    STATE(86), 1,
      sym_comment,
    STATE(87), 1,
      sym_typeHint,
  [2425] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(234), 1,
      anon_sym_EQ,
    ACTIONS(236), 1,
      anon_sym_SEMI,
    STATE(87), 1,
      sym_comment,
  [2438] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(238), 1,
      anon_sym_EQ,
    ACTIONS(240), 1,
      anon_sym_SEMI,
    STATE(88), 1,
      sym_comment,
  [2451] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(89), 1,
      sym_comment,
    ACTIONS(242), 2,
      anon_sym_EQ,
      anon_sym_SEMI,
  [2462] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(244), 1,
      sym_identifier,
    STATE(90), 1,
      sym_comment,
  [2472] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(246), 1,
      ts_builtin_sym_end,
    STATE(91), 1,
      sym_comment,
  [2482] = 3,
    ACTIONS(248), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(250), 1,
      aux_sym_comment_token1,
    STATE(92), 1,
      sym_comment,
  [2492] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(252), 1,
      sym_identifier,
    STATE(93), 1,
      sym_comment,
  [2502] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(254), 1,
      sym_identifier,
    STATE(94), 1,
      sym_comment,
  [2512] = 1,
    ACTIONS(256), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(16)] = 0,
  [SMALL_STATE(17)] = 45,
  [SMALL_STATE(18)] = 80,
  [SMALL_STATE(19)] = 115,
  [SMALL_STATE(20)] = 168,
  [SMALL_STATE(21)] = 207,
  [SMALL_STATE(22)] = 242,
  [SMALL_STATE(23)] = 293,
  [SMALL_STATE(24)] = 328,
  [SMALL_STATE(25)] = 375,
  [SMALL_STATE(26)] = 424,
  [SMALL_STATE(27)] = 463,
  [SMALL_STATE(28)] = 498,
  [SMALL_STATE(29)] = 539,
  [SMALL_STATE(30)] = 579,
  [SMALL_STATE(31)] = 619,
  [SMALL_STATE(32)] = 659,
  [SMALL_STATE(33)] = 699,
  [SMALL_STATE(34)] = 739,
  [SMALL_STATE(35)] = 779,
  [SMALL_STATE(36)] = 819,
  [SMALL_STATE(37)] = 859,
  [SMALL_STATE(38)] = 899,
  [SMALL_STATE(39)] = 939,
  [SMALL_STATE(40)] = 979,
  [SMALL_STATE(41)] = 1019,
  [SMALL_STATE(42)] = 1059,
  [SMALL_STATE(43)] = 1099,
  [SMALL_STATE(44)] = 1139,
  [SMALL_STATE(45)] = 1179,
  [SMALL_STATE(46)] = 1219,
  [SMALL_STATE(47)] = 1259,
  [SMALL_STATE(48)] = 1299,
  [SMALL_STATE(49)] = 1339,
  [SMALL_STATE(50)] = 1365,
  [SMALL_STATE(51)] = 1391,
  [SMALL_STATE(52)] = 1417,
  [SMALL_STATE(53)] = 1443,
  [SMALL_STATE(54)] = 1471,
  [SMALL_STATE(55)] = 1497,
  [SMALL_STATE(56)] = 1523,
  [SMALL_STATE(57)] = 1549,
  [SMALL_STATE(58)] = 1575,
  [SMALL_STATE(59)] = 1601,
  [SMALL_STATE(60)] = 1627,
  [SMALL_STATE(61)] = 1653,
  [SMALL_STATE(62)] = 1681,
  [SMALL_STATE(63)] = 1707,
  [SMALL_STATE(64)] = 1733,
  [SMALL_STATE(65)] = 1759,
  [SMALL_STATE(66)] = 1800,
  [SMALL_STATE(67)] = 1841,
  [SMALL_STATE(68)] = 1866,
  [SMALL_STATE(69)] = 1891,
  [SMALL_STATE(70)] = 1916,
  [SMALL_STATE(71)] = 1941,
  [SMALL_STATE(72)] = 1966,
  [SMALL_STATE(73)] = 2007,
  [SMALL_STATE(74)] = 2032,
  [SMALL_STATE(75)] = 2057,
  [SMALL_STATE(76)] = 2082,
  [SMALL_STATE(77)] = 2107,
  [SMALL_STATE(78)] = 2148,
  [SMALL_STATE(79)] = 2173,
  [SMALL_STATE(80)] = 2198,
  [SMALL_STATE(81)] = 2239,
  [SMALL_STATE(82)] = 2280,
  [SMALL_STATE(83)] = 2321,
  [SMALL_STATE(84)] = 2346,
  [SMALL_STATE(85)] = 2387,
  [SMALL_STATE(86)] = 2406,
  [SMALL_STATE(87)] = 2425,
  [SMALL_STATE(88)] = 2438,
  [SMALL_STATE(89)] = 2451,
  [SMALL_STATE(90)] = 2462,
  [SMALL_STATE(91)] = 2472,
  [SMALL_STATE(92)] = 2482,
  [SMALL_STATE(93)] = 2492,
  [SMALL_STATE(94)] = 2502,
  [SMALL_STATE(95)] = 2512,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(94),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [45] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [47] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [51] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [53] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [55] = {.entry = {.count = 1, .reusable = false}}, SHIFT(93),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [59] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [65] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [68] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(94),
  [71] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [74] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(34),
  [77] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [80] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(30),
  [83] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [86] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [89] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [94] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(93),
  [97] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [100] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(44),
  [103] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(45),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [110] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__primary, 1, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__primary, 1, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_equality, 3, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_equality, 3, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expression, 1, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 1, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unary, 2, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unary, 2, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assignment, 3, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment, 3, 0, 0),
  [132] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary, 3, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary, 3, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_logical, 3, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_logical, 3, 0, 0),
  [140] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bool, 1, 0, 0),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bool, 1, 0, 0),
  [144] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comparison, 3, 0, 0),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comparison, 3, 0, 0),
  [148] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ifStatement, 3, 0, 0),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ifStatement, 3, 0, 0),
  [152] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 2, 0, 0),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2, 0, 0),
  [156] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expressionStatement, 2, 0, 0),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expressionStatement, 2, 0, 0),
  [160] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 3, 0, 0),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 0),
  [164] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [166] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_printStatement, 3, 0, 0),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_printStatement, 3, 0, 0),
  [170] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ifStatement, 5, 0, 0),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ifStatement, 5, 0, 0),
  [174] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statement, 1, 0, 0),
  [176] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__statement, 1, 0, 0),
  [178] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [188] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_varDeclaration, 3, 0, 0),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_varDeclaration, 3, 0, 0),
  [192] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_varDeclaration, 4, 0, 0),
  [194] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_varDeclaration, 4, 0, 0),
  [196] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_varDeclaration, 5, 0, 0),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_varDeclaration, 5, 0, 0),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [202] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_varDeclaration, 6, 0, 0),
  [204] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_varDeclaration, 6, 0, 0),
  [206] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 0),
  [208] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 0),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__declaration, 1, 0, 0),
  [212] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__declaration, 1, 0, 0),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [242] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_typeHint, 2, 0, 0),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [246] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [248] = {.entry = {.count = 1, .reusable = false}}, SHIFT(92),
  [250] = {.entry = {.count = 1, .reusable = false}}, SHIFT(95),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [256] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_flow(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
