#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 50
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 47
#define ALIAS_COUNT 0
#define TOKEN_COUNT 29
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define PRODUCTION_ID_COUNT 1

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_var = 2,
  anon_sym_const = 3,
  anon_sym_EQ = 4,
  anon_sym_SEMI = 5,
  anon_sym_print = 6,
  anon_sym_DASH = 7,
  anon_sym_BANG = 8,
  anon_sym_SLASH = 9,
  anon_sym_STAR = 10,
  anon_sym_PLUS = 11,
  anon_sym_DOT = 12,
  anon_sym_LT = 13,
  anon_sym_LT_EQ = 14,
  anon_sym_GT_EQ = 15,
  anon_sym_GT = 16,
  anon_sym_BANG_EQ = 17,
  anon_sym_EQ_EQ = 18,
  anon_sym_and = 19,
  anon_sym_or = 20,
  sym_number = 21,
  sym_string = 22,
  anon_sym_true = 23,
  anon_sym_false = 24,
  sym_null = 25,
  anon_sym_COLON = 26,
  anon_sym_SLASH_SLASH = 27,
  aux_sym_comment_token1 = 28,
  sym_source_file = 29,
  sym__declaration = 30,
  sym_varDeclaration = 31,
  sym__statement = 32,
  sym_expressionStatement = 33,
  sym_printStatement = 34,
  sym__expression = 35,
  sym_unary = 36,
  sym_binary = 37,
  sym_comparison = 38,
  sym_equality = 39,
  sym_logical = 40,
  sym_assignment = 41,
  sym__primary = 42,
  sym_bool = 43,
  sym__typeHint = 44,
  sym_comment = 45,
  aux_sym_source_file_repeat1 = 46,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_var] = "var",
  [anon_sym_const] = "const",
  [anon_sym_EQ] = "=",
  [anon_sym_SEMI] = ";",
  [anon_sym_print] = "print",
  [anon_sym_DASH] = "-",
  [anon_sym_BANG] = "!",
  [anon_sym_SLASH] = "/",
  [anon_sym_STAR] = "*",
  [anon_sym_PLUS] = "+",
  [anon_sym_DOT] = ".",
  [anon_sym_LT] = "<",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_GT] = ">",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_and] = "and",
  [anon_sym_or] = "or",
  [sym_number] = "number",
  [sym_string] = "string",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_null] = "null",
  [anon_sym_COLON] = ":",
  [anon_sym_SLASH_SLASH] = "//",
  [aux_sym_comment_token1] = "comment_token1",
  [sym_source_file] = "source_file",
  [sym__declaration] = "_declaration",
  [sym_varDeclaration] = "varDeclaration",
  [sym__statement] = "_statement",
  [sym_expressionStatement] = "expressionStatement",
  [sym_printStatement] = "printStatement",
  [sym__expression] = "_expression",
  [sym_unary] = "unary",
  [sym_binary] = "binary",
  [sym_comparison] = "comparison",
  [sym_equality] = "equality",
  [sym_logical] = "logical",
  [sym_assignment] = "assignment",
  [sym__primary] = "_primary",
  [sym_bool] = "bool",
  [sym__typeHint] = "_typeHint",
  [sym_comment] = "comment",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_var] = anon_sym_var,
  [anon_sym_const] = anon_sym_const,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_print] = anon_sym_print,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_and] = anon_sym_and,
  [anon_sym_or] = anon_sym_or,
  [sym_number] = sym_number,
  [sym_string] = sym_string,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_null] = sym_null,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_SLASH_SLASH] = anon_sym_SLASH_SLASH,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [sym_source_file] = sym_source_file,
  [sym__declaration] = sym__declaration,
  [sym_varDeclaration] = sym_varDeclaration,
  [sym__statement] = sym__statement,
  [sym_expressionStatement] = sym_expressionStatement,
  [sym_printStatement] = sym_printStatement,
  [sym__expression] = sym__expression,
  [sym_unary] = sym_unary,
  [sym_binary] = sym_binary,
  [sym_comparison] = sym_comparison,
  [sym_equality] = sym_equality,
  [sym_logical] = sym_logical,
  [sym_assignment] = sym_assignment,
  [sym__primary] = sym__primary,
  [sym_bool] = sym_bool,
  [sym__typeHint] = sym__typeHint,
  [sym_comment] = sym_comment,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_var] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_const] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_print] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_and] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_or] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_null] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_SLASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__declaration] = {
    .visible = false,
    .named = true,
  },
  [sym_varDeclaration] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_expressionStatement] = {
    .visible = true,
    .named = true,
  },
  [sym_printStatement] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_unary] = {
    .visible = true,
    .named = true,
  },
  [sym_binary] = {
    .visible = true,
    .named = true,
  },
  [sym_comparison] = {
    .visible = true,
    .named = true,
  },
  [sym_equality] = {
    .visible = true,
    .named = true,
  },
  [sym_logical] = {
    .visible = true,
    .named = true,
  },
  [sym_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym__primary] = {
    .visible = false,
    .named = true,
  },
  [sym_bool] = {
    .visible = true,
    .named = true,
  },
  [sym__typeHint] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(7);
      ADVANCE_MAP(
        '!', 12,
        '"', 2,
        '*', 14,
        '+', 15,
        '-', 10,
        '.', 16,
        '/', 13,
        ':', 27,
        ';', 9,
        '<', 17,
        '=', 8,
        '>', 20,
      );
      if (lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(23);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '!', 4,
        '*', 14,
        '+', 15,
        '-', 10,
        '.', 16,
        '/', 13,
        ';', 9,
        '<', 17,
        '=', 8,
        '>', 20,
      );
      if (lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(25);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '/') ADVANCE(28);
      END_STATE();
    case 4:
      if (lookahead == '=') ADVANCE(21);
      END_STATE();
    case 5:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(24);
      END_STATE();
    case 6:
      if (eof) ADVANCE(7);
      if (lookahead == '!') ADVANCE(11);
      if (lookahead == '"') ADVANCE(2);
      if (lookahead == '-') ADVANCE(10);
      if (lookahead == '/') ADVANCE(3);
      if (lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(6);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(23);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(22);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_BANG);
      if (lookahead == '=') ADVANCE(21);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '/') ADVANCE(28);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(18);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(19);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(5);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(23);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(32);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '/') ADVANCE(31);
      if (lookahead == '\r' ||
          lookahead == ' ') ADVANCE(30);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(32);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '/') ADVANCE(29);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(32);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(32);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ADVANCE_MAP(
        'a', 1,
        'c', 2,
        'f', 3,
        'n', 4,
        'o', 5,
        'p', 6,
        't', 7,
        'v', 8,
      );
      if (lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'n') ADVANCE(9);
      END_STATE();
    case 2:
      if (lookahead == 'o') ADVANCE(10);
      END_STATE();
    case 3:
      if (lookahead == 'a') ADVANCE(11);
      END_STATE();
    case 4:
      if (lookahead == 'u') ADVANCE(12);
      END_STATE();
    case 5:
      if (lookahead == 'r') ADVANCE(13);
      END_STATE();
    case 6:
      if (lookahead == 'r') ADVANCE(14);
      END_STATE();
    case 7:
      if (lookahead == 'r') ADVANCE(15);
      END_STATE();
    case 8:
      if (lookahead == 'a') ADVANCE(16);
      END_STATE();
    case 9:
      if (lookahead == 'd') ADVANCE(17);
      END_STATE();
    case 10:
      if (lookahead == 'n') ADVANCE(18);
      END_STATE();
    case 11:
      if (lookahead == 'l') ADVANCE(19);
      END_STATE();
    case 12:
      if (lookahead == 'l') ADVANCE(20);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_or);
      END_STATE();
    case 14:
      if (lookahead == 'i') ADVANCE(21);
      END_STATE();
    case 15:
      if (lookahead == 'u') ADVANCE(22);
      END_STATE();
    case 16:
      if (lookahead == 'r') ADVANCE(23);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_and);
      END_STATE();
    case 18:
      if (lookahead == 's') ADVANCE(24);
      END_STATE();
    case 19:
      if (lookahead == 's') ADVANCE(25);
      END_STATE();
    case 20:
      if (lookahead == 'l') ADVANCE(26);
      END_STATE();
    case 21:
      if (lookahead == 'n') ADVANCE(27);
      END_STATE();
    case 22:
      if (lookahead == 'e') ADVANCE(28);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_var);
      END_STATE();
    case 24:
      if (lookahead == 't') ADVANCE(29);
      END_STATE();
    case 25:
      if (lookahead == 'e') ADVANCE(30);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_null);
      END_STATE();
    case 27:
      if (lookahead == 't') ADVANCE(31);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_const);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_print);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 6},
  [2] = {.lex_state = 6},
  [3] = {.lex_state = 6},
  [4] = {.lex_state = 6},
  [5] = {.lex_state = 6},
  [6] = {.lex_state = 6},
  [7] = {.lex_state = 6},
  [8] = {.lex_state = 6},
  [9] = {.lex_state = 6},
  [10] = {.lex_state = 6},
  [11] = {.lex_state = 6},
  [12] = {.lex_state = 6},
  [13] = {.lex_state = 6},
  [14] = {.lex_state = 6},
  [15] = {.lex_state = 6},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 1},
  [21] = {.lex_state = 1},
  [22] = {.lex_state = 1},
  [23] = {.lex_state = 1},
  [24] = {.lex_state = 1},
  [25] = {.lex_state = 1},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 1},
  [30] = {.lex_state = 1},
  [31] = {.lex_state = 1},
  [32] = {.lex_state = 1},
  [33] = {.lex_state = 6},
  [34] = {.lex_state = 6},
  [35] = {.lex_state = 6},
  [36] = {.lex_state = 6},
  [37] = {.lex_state = 6},
  [38] = {.lex_state = 6},
  [39] = {.lex_state = 6},
  [40] = {.lex_state = 6},
  [41] = {.lex_state = 6},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 30},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {(TSStateId)(-1)},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [sym_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_var] = ACTIONS(1),
    [anon_sym_const] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_print] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_and] = ACTIONS(1),
    [anon_sym_or] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_null] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
  [1] = {
    [sym_source_file] = STATE(45),
    [sym__declaration] = STATE(33),
    [sym_varDeclaration] = STATE(36),
    [sym__statement] = STATE(36),
    [sym_expressionStatement] = STATE(37),
    [sym_printStatement] = STATE(37),
    [sym__expression] = STATE(20),
    [sym_unary] = STATE(21),
    [sym_binary] = STATE(21),
    [sym_comparison] = STATE(21),
    [sym_equality] = STATE(21),
    [sym_logical] = STATE(21),
    [sym_assignment] = STATE(21),
    [sym__primary] = STATE(21),
    [sym_bool] = STATE(31),
    [sym_comment] = STATE(1),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_identifier] = ACTIONS(7),
    [anon_sym_var] = ACTIONS(9),
    [anon_sym_const] = ACTIONS(9),
    [anon_sym_print] = ACTIONS(11),
    [anon_sym_DASH] = ACTIONS(13),
    [anon_sym_BANG] = ACTIONS(13),
    [sym_number] = ACTIONS(15),
    [sym_string] = ACTIONS(15),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [sym_null] = ACTIONS(19),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
  [2] = {
    [sym__declaration] = STATE(33),
    [sym_varDeclaration] = STATE(36),
    [sym__statement] = STATE(36),
    [sym_expressionStatement] = STATE(37),
    [sym_printStatement] = STATE(37),
    [sym__expression] = STATE(20),
    [sym_unary] = STATE(21),
    [sym_binary] = STATE(21),
    [sym_comparison] = STATE(21),
    [sym_equality] = STATE(21),
    [sym_logical] = STATE(21),
    [sym_assignment] = STATE(21),
    [sym__primary] = STATE(21),
    [sym_bool] = STATE(31),
    [sym_comment] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(21),
    [sym_identifier] = ACTIONS(7),
    [anon_sym_var] = ACTIONS(9),
    [anon_sym_const] = ACTIONS(9),
    [anon_sym_print] = ACTIONS(11),
    [anon_sym_DASH] = ACTIONS(13),
    [anon_sym_BANG] = ACTIONS(13),
    [sym_number] = ACTIONS(15),
    [sym_string] = ACTIONS(15),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [sym_null] = ACTIONS(19),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
  [3] = {
    [sym__declaration] = STATE(33),
    [sym_varDeclaration] = STATE(36),
    [sym__statement] = STATE(36),
    [sym_expressionStatement] = STATE(37),
    [sym_printStatement] = STATE(37),
    [sym__expression] = STATE(20),
    [sym_unary] = STATE(21),
    [sym_binary] = STATE(21),
    [sym_comparison] = STATE(21),
    [sym_equality] = STATE(21),
    [sym_logical] = STATE(21),
    [sym_assignment] = STATE(21),
    [sym__primary] = STATE(21),
    [sym_bool] = STATE(31),
    [sym_comment] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(23),
    [sym_identifier] = ACTIONS(25),
    [anon_sym_var] = ACTIONS(28),
    [anon_sym_const] = ACTIONS(28),
    [anon_sym_print] = ACTIONS(31),
    [anon_sym_DASH] = ACTIONS(34),
    [anon_sym_BANG] = ACTIONS(34),
    [sym_number] = ACTIONS(37),
    [sym_string] = ACTIONS(37),
    [anon_sym_true] = ACTIONS(40),
    [anon_sym_false] = ACTIONS(40),
    [sym_null] = ACTIONS(43),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 10,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(19), 1,
      sym_null,
    STATE(4), 1,
      sym_comment,
    STATE(25), 1,
      sym__expression,
    STATE(31), 1,
      sym_bool,
    ACTIONS(13), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(15), 2,
      sym_number,
      sym_string,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(21), 7,
      sym_unary,
      sym_binary,
      sym_comparison,
      sym_equality,
      sym_logical,
      sym_assignment,
      sym__primary,
  [40] = 10,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(19), 1,
      sym_null,
    STATE(5), 1,
      sym_comment,
    STATE(31), 1,
      sym_bool,
    STATE(32), 1,
      sym__expression,
    ACTIONS(13), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(15), 2,
      sym_number,
      sym_string,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(21), 7,
      sym_unary,
      sym_binary,
      sym_comparison,
      sym_equality,
      sym_logical,
      sym_assignment,
      sym__primary,
  [80] = 10,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(19), 1,
      sym_null,
    STATE(6), 1,
      sym_comment,
    STATE(22), 1,
      sym__expression,
    STATE(31), 1,
      sym_bool,
    ACTIONS(13), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(15), 2,
      sym_number,
      sym_string,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(21), 7,
      sym_unary,
      sym_binary,
      sym_comparison,
      sym_equality,
      sym_logical,
      sym_assignment,
      sym__primary,
  [120] = 10,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(19), 1,
      sym_null,
    STATE(7), 1,
      sym_comment,
    STATE(23), 1,
      sym__expression,
    STATE(31), 1,
      sym_bool,
    ACTIONS(13), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(15), 2,
      sym_number,
      sym_string,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(21), 7,
      sym_unary,
      sym_binary,
      sym_comparison,
      sym_equality,
      sym_logical,
      sym_assignment,
      sym__primary,
  [160] = 10,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(19), 1,
      sym_null,
    STATE(8), 1,
      sym_comment,
    STATE(24), 1,
      sym__expression,
    STATE(31), 1,
      sym_bool,
    ACTIONS(13), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(15), 2,
      sym_number,
      sym_string,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(21), 7,
      sym_unary,
      sym_binary,
      sym_comparison,
      sym_equality,
      sym_logical,
      sym_assignment,
      sym__primary,
  [200] = 10,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(19), 1,
      sym_null,
    STATE(9), 1,
      sym_comment,
    STATE(26), 1,
      sym__expression,
    STATE(31), 1,
      sym_bool,
    ACTIONS(13), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(15), 2,
      sym_number,
      sym_string,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(21), 7,
      sym_unary,
      sym_binary,
      sym_comparison,
      sym_equality,
      sym_logical,
      sym_assignment,
      sym__primary,
  [240] = 10,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(19), 1,
      sym_null,
    STATE(10), 1,
      sym_comment,
    STATE(27), 1,
      sym__expression,
    STATE(31), 1,
      sym_bool,
    ACTIONS(13), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(15), 2,
      sym_number,
      sym_string,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(21), 7,
      sym_unary,
      sym_binary,
      sym_comparison,
      sym_equality,
      sym_logical,
      sym_assignment,
      sym__primary,
  [280] = 10,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(19), 1,
      sym_null,
    STATE(11), 1,
      sym_comment,
    STATE(28), 1,
      sym__expression,
    STATE(31), 1,
      sym_bool,
    ACTIONS(13), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(15), 2,
      sym_number,
      sym_string,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(21), 7,
      sym_unary,
      sym_binary,
      sym_comparison,
      sym_equality,
      sym_logical,
      sym_assignment,
      sym__primary,
  [320] = 10,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(19), 1,
      sym_null,
    STATE(12), 1,
      sym_comment,
    STATE(29), 1,
      sym__expression,
    STATE(31), 1,
      sym_bool,
    ACTIONS(13), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(15), 2,
      sym_number,
      sym_string,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(21), 7,
      sym_unary,
      sym_binary,
      sym_comparison,
      sym_equality,
      sym_logical,
      sym_assignment,
      sym__primary,
  [360] = 10,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(19), 1,
      sym_null,
    STATE(13), 1,
      sym_comment,
    STATE(17), 1,
      sym__expression,
    STATE(31), 1,
      sym_bool,
    ACTIONS(13), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(15), 2,
      sym_number,
      sym_string,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(21), 7,
      sym_unary,
      sym_binary,
      sym_comparison,
      sym_equality,
      sym_logical,
      sym_assignment,
      sym__primary,
  [400] = 10,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(19), 1,
      sym_null,
    STATE(14), 1,
      sym_comment,
    STATE(30), 1,
      sym__expression,
    STATE(31), 1,
      sym_bool,
    ACTIONS(13), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(15), 2,
      sym_number,
      sym_string,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(21), 7,
      sym_unary,
      sym_binary,
      sym_comparison,
      sym_equality,
      sym_logical,
      sym_assignment,
      sym__primary,
  [440] = 10,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(19), 1,
      sym_null,
    STATE(15), 1,
      sym_comment,
    STATE(18), 1,
      sym__expression,
    STATE(31), 1,
      sym_bool,
    ACTIONS(13), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(15), 2,
      sym_number,
      sym_string,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(21), 7,
      sym_unary,
      sym_binary,
      sym_comparison,
      sym_equality,
      sym_logical,
      sym_assignment,
      sym__primary,
  [480] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(46), 1,
      anon_sym_EQ,
    STATE(16), 1,
      sym_comment,
    ACTIONS(50), 3,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(48), 11,
      anon_sym_SEMI,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DOT,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_and,
      anon_sym_or,
  [508] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(52), 1,
      anon_sym_SEMI,
    ACTIONS(56), 1,
      anon_sym_SLASH,
    ACTIONS(58), 1,
      anon_sym_STAR,
    ACTIONS(60), 1,
      anon_sym_DOT,
    ACTIONS(68), 1,
      anon_sym_and,
    ACTIONS(70), 1,
      anon_sym_or,
    STATE(17), 1,
      sym_comment,
    ACTIONS(54), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(62), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(64), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(66), 2,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
  [549] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(18), 1,
      sym_comment,
    ACTIONS(74), 3,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(72), 11,
      anon_sym_SEMI,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DOT,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_and,
      anon_sym_or,
  [574] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(19), 1,
      sym_comment,
    ACTIONS(78), 3,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(76), 11,
      anon_sym_SEMI,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DOT,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_and,
      anon_sym_or,
  [599] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(56), 1,
      anon_sym_SLASH,
    ACTIONS(58), 1,
      anon_sym_STAR,
    ACTIONS(60), 1,
      anon_sym_DOT,
    ACTIONS(68), 1,
      anon_sym_and,
    ACTIONS(70), 1,
      anon_sym_or,
    ACTIONS(80), 1,
      anon_sym_SEMI,
    STATE(20), 1,
      sym_comment,
    ACTIONS(54), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(62), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(64), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(66), 2,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
  [640] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(21), 1,
      sym_comment,
    ACTIONS(84), 3,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(82), 11,
      anon_sym_SEMI,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DOT,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_and,
      anon_sym_or,
  [665] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(56), 1,
      anon_sym_SLASH,
    ACTIONS(58), 1,
      anon_sym_STAR,
    ACTIONS(60), 1,
      anon_sym_DOT,
    ACTIONS(68), 1,
      anon_sym_and,
    ACTIONS(70), 1,
      anon_sym_or,
    ACTIONS(86), 1,
      anon_sym_SEMI,
    STATE(22), 1,
      sym_comment,
    ACTIONS(54), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(62), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(64), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(66), 2,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
  [706] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(56), 1,
      anon_sym_SLASH,
    ACTIONS(58), 1,
      anon_sym_STAR,
    STATE(23), 1,
      sym_comment,
    ACTIONS(90), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(88), 10,
      anon_sym_SEMI,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_DOT,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_and,
      anon_sym_or,
  [735] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(24), 1,
      sym_comment,
    ACTIONS(90), 3,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(88), 11,
      anon_sym_SEMI,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DOT,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_and,
      anon_sym_or,
  [760] = 11,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(56), 1,
      anon_sym_SLASH,
    ACTIONS(58), 1,
      anon_sym_STAR,
    ACTIONS(68), 1,
      anon_sym_and,
    ACTIONS(70), 1,
      anon_sym_or,
    STATE(25), 1,
      sym_comment,
    ACTIONS(54), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(62), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(64), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(66), 2,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
    ACTIONS(88), 2,
      anon_sym_SEMI,
      anon_sym_DOT,
  [799] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(56), 1,
      anon_sym_SLASH,
    ACTIONS(58), 1,
      anon_sym_STAR,
    STATE(26), 1,
      sym_comment,
    ACTIONS(54), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(94), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(92), 8,
      anon_sym_SEMI,
      anon_sym_DOT,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_and,
      anon_sym_or,
  [830] = 8,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(56), 1,
      anon_sym_SLASH,
    ACTIONS(58), 1,
      anon_sym_STAR,
    STATE(27), 1,
      sym_comment,
    ACTIONS(54), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(62), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(64), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(96), 6,
      anon_sym_SEMI,
      anon_sym_DOT,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_and,
      anon_sym_or,
  [863] = 9,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(56), 1,
      anon_sym_SLASH,
    ACTIONS(58), 1,
      anon_sym_STAR,
    STATE(28), 1,
      sym_comment,
    ACTIONS(54), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(62), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(64), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(66), 2,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
    ACTIONS(98), 4,
      anon_sym_SEMI,
      anon_sym_DOT,
      anon_sym_and,
      anon_sym_or,
  [898] = 10,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(56), 1,
      anon_sym_SLASH,
    ACTIONS(58), 1,
      anon_sym_STAR,
    ACTIONS(68), 1,
      anon_sym_and,
    STATE(29), 1,
      sym_comment,
    ACTIONS(54), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(62), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(64), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(66), 2,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
    ACTIONS(98), 3,
      anon_sym_SEMI,
      anon_sym_DOT,
      anon_sym_or,
  [935] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(56), 1,
      anon_sym_SLASH,
    ACTIONS(58), 1,
      anon_sym_STAR,
    ACTIONS(60), 1,
      anon_sym_DOT,
    ACTIONS(68), 1,
      anon_sym_and,
    ACTIONS(70), 1,
      anon_sym_or,
    ACTIONS(100), 1,
      anon_sym_SEMI,
    STATE(30), 1,
      sym_comment,
    ACTIONS(54), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(62), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(64), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(66), 2,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
  [976] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(31), 1,
      sym_comment,
    ACTIONS(50), 3,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(48), 11,
      anon_sym_SEMI,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DOT,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_and,
      anon_sym_or,
  [1001] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(56), 1,
      anon_sym_SLASH,
    ACTIONS(58), 1,
      anon_sym_STAR,
    ACTIONS(60), 1,
      anon_sym_DOT,
    ACTIONS(68), 1,
      anon_sym_and,
    ACTIONS(70), 1,
      anon_sym_or,
    ACTIONS(102), 1,
      anon_sym_SEMI,
    STATE(32), 1,
      sym_comment,
    ACTIONS(54), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(62), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(64), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(66), 2,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
  [1042] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(33), 1,
      sym_comment,
    ACTIONS(104), 5,
      ts_builtin_sym_end,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
      sym_string,
    ACTIONS(106), 7,
      anon_sym_var,
      anon_sym_const,
      anon_sym_print,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_identifier,
  [1065] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(34), 1,
      sym_comment,
    ACTIONS(108), 5,
      ts_builtin_sym_end,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
      sym_string,
    ACTIONS(110), 7,
      anon_sym_var,
      anon_sym_const,
      anon_sym_print,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_identifier,
  [1088] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(35), 1,
      sym_comment,
    ACTIONS(112), 5,
      ts_builtin_sym_end,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
      sym_string,
    ACTIONS(114), 7,
      anon_sym_var,
      anon_sym_const,
      anon_sym_print,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_identifier,
  [1111] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(36), 1,
      sym_comment,
    ACTIONS(116), 5,
      ts_builtin_sym_end,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
      sym_string,
    ACTIONS(118), 7,
      anon_sym_var,
      anon_sym_const,
      anon_sym_print,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_identifier,
  [1134] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(37), 1,
      sym_comment,
    ACTIONS(120), 5,
      ts_builtin_sym_end,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
      sym_string,
    ACTIONS(122), 7,
      anon_sym_var,
      anon_sym_const,
      anon_sym_print,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_identifier,
  [1157] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(38), 1,
      sym_comment,
    ACTIONS(124), 5,
      ts_builtin_sym_end,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
      sym_string,
    ACTIONS(126), 7,
      anon_sym_var,
      anon_sym_const,
      anon_sym_print,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_identifier,
  [1180] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(39), 1,
      sym_comment,
    ACTIONS(128), 5,
      ts_builtin_sym_end,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
      sym_string,
    ACTIONS(130), 7,
      anon_sym_var,
      anon_sym_const,
      anon_sym_print,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_identifier,
  [1203] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(40), 1,
      sym_comment,
    ACTIONS(132), 5,
      ts_builtin_sym_end,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
      sym_string,
    ACTIONS(134), 7,
      anon_sym_var,
      anon_sym_const,
      anon_sym_print,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_identifier,
  [1226] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(41), 1,
      sym_comment,
    ACTIONS(136), 5,
      ts_builtin_sym_end,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
      sym_string,
    ACTIONS(138), 7,
      anon_sym_var,
      anon_sym_const,
      anon_sym_print,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_identifier,
  [1249] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(140), 1,
      anon_sym_EQ,
    ACTIONS(142), 1,
      anon_sym_SEMI,
    ACTIONS(144), 1,
      anon_sym_COLON,
    STATE(42), 1,
      sym_comment,
    STATE(44), 1,
      sym__typeHint,
  [1268] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(43), 1,
      sym_comment,
    ACTIONS(146), 2,
      anon_sym_EQ,
      anon_sym_SEMI,
  [1279] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(148), 1,
      anon_sym_EQ,
    ACTIONS(150), 1,
      anon_sym_SEMI,
    STATE(44), 1,
      sym_comment,
  [1292] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(152), 1,
      ts_builtin_sym_end,
    STATE(45), 1,
      sym_comment,
  [1302] = 3,
    ACTIONS(154), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(156), 1,
      aux_sym_comment_token1,
    STATE(46), 1,
      sym_comment,
  [1312] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(158), 1,
      sym_identifier,
    STATE(47), 1,
      sym_comment,
  [1322] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(160), 1,
      sym_identifier,
    STATE(48), 1,
      sym_comment,
  [1332] = 1,
    ACTIONS(162), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 40,
  [SMALL_STATE(6)] = 80,
  [SMALL_STATE(7)] = 120,
  [SMALL_STATE(8)] = 160,
  [SMALL_STATE(9)] = 200,
  [SMALL_STATE(10)] = 240,
  [SMALL_STATE(11)] = 280,
  [SMALL_STATE(12)] = 320,
  [SMALL_STATE(13)] = 360,
  [SMALL_STATE(14)] = 400,
  [SMALL_STATE(15)] = 440,
  [SMALL_STATE(16)] = 480,
  [SMALL_STATE(17)] = 508,
  [SMALL_STATE(18)] = 549,
  [SMALL_STATE(19)] = 574,
  [SMALL_STATE(20)] = 599,
  [SMALL_STATE(21)] = 640,
  [SMALL_STATE(22)] = 665,
  [SMALL_STATE(23)] = 706,
  [SMALL_STATE(24)] = 735,
  [SMALL_STATE(25)] = 760,
  [SMALL_STATE(26)] = 799,
  [SMALL_STATE(27)] = 830,
  [SMALL_STATE(28)] = 863,
  [SMALL_STATE(29)] = 898,
  [SMALL_STATE(30)] = 935,
  [SMALL_STATE(31)] = 976,
  [SMALL_STATE(32)] = 1001,
  [SMALL_STATE(33)] = 1042,
  [SMALL_STATE(34)] = 1065,
  [SMALL_STATE(35)] = 1088,
  [SMALL_STATE(36)] = 1111,
  [SMALL_STATE(37)] = 1134,
  [SMALL_STATE(38)] = 1157,
  [SMALL_STATE(39)] = 1180,
  [SMALL_STATE(40)] = 1203,
  [SMALL_STATE(41)] = 1226,
  [SMALL_STATE(42)] = 1249,
  [SMALL_STATE(43)] = 1268,
  [SMALL_STATE(44)] = 1279,
  [SMALL_STATE(45)] = 1292,
  [SMALL_STATE(46)] = 1302,
  [SMALL_STATE(47)] = 1312,
  [SMALL_STATE(48)] = 1322,
  [SMALL_STATE(49)] = 1332,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [25] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [28] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(47),
  [31] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [40] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [43] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [46] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__primary, 1, 0, 0),
  [50] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__primary, 1, 0, 0),
  [52] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [56] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [62] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unary, 2, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unary, 2, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bool, 1, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bool, 1, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 1, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expression, 1, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment, 3, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary, 3, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary, 3, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comparison, 3, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comparison, 3, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_equality, 3, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_logical, 3, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_printStatement, 3, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_printStatement, 3, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expressionStatement, 2, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expressionStatement, 2, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__declaration, 1, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__declaration, 1, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statement, 1, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__statement, 1, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_varDeclaration, 3, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_varDeclaration, 3, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_varDeclaration, 4, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_varDeclaration, 4, 0, 0),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_varDeclaration, 5, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_varDeclaration, 5, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_varDeclaration, 6, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_varDeclaration, 6, 0, 0),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__typeHint, 2, 0, 0),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [152] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [154] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [156] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_flow(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
