#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 84
#define LARGE_STATE_COUNT 13
#define SYMBOL_COUNT 54
#define ALIAS_COUNT 0
#define TOKEN_COUNT 33
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define PRODUCTION_ID_COUNT 1

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_var = 2,
  anon_sym_const = 3,
  anon_sym_EQ = 4,
  anon_sym_SEMI = 5,
  anon_sym_LBRACE = 6,
  anon_sym_RBRACE = 7,
  anon_sym_if = 8,
  anon_sym_else = 9,
  anon_sym_print = 10,
  anon_sym_DASH = 11,
  anon_sym_BANG = 12,
  anon_sym_SLASH = 13,
  anon_sym_STAR = 14,
  anon_sym_PLUS = 15,
  anon_sym_DOT = 16,
  anon_sym_LT = 17,
  anon_sym_LT_EQ = 18,
  anon_sym_GT_EQ = 19,
  anon_sym_GT = 20,
  anon_sym_BANG_EQ = 21,
  anon_sym_EQ_EQ = 22,
  anon_sym_and = 23,
  anon_sym_or = 24,
  sym_number = 25,
  sym_string = 26,
  anon_sym_true = 27,
  anon_sym_false = 28,
  sym_null = 29,
  anon_sym_COLON = 30,
  anon_sym_SLASH_SLASH = 31,
  aux_sym_comment_token1 = 32,
  sym_source_file = 33,
  sym__declaration = 34,
  sym_varDeclaration = 35,
  sym__statement = 36,
  sym__block = 37,
  sym_ifStatement = 38,
  sym_expressionStatement = 39,
  sym_printStatement = 40,
  sym__expression = 41,
  sym_unary = 42,
  sym_binary = 43,
  sym_comparison = 44,
  sym_equality = 45,
  sym_logical = 46,
  sym_assignment = 47,
  sym__primary = 48,
  sym_bool = 49,
  sym__typeHint = 50,
  sym_comment = 51,
  aux_sym_source_file_repeat1 = 52,
  aux_sym__block_repeat1 = 53,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_var] = "var",
  [anon_sym_const] = "const",
  [anon_sym_EQ] = "=",
  [anon_sym_SEMI] = ";",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_if] = "if",
  [anon_sym_else] = "else",
  [anon_sym_print] = "print",
  [anon_sym_DASH] = "-",
  [anon_sym_BANG] = "!",
  [anon_sym_SLASH] = "/",
  [anon_sym_STAR] = "*",
  [anon_sym_PLUS] = "+",
  [anon_sym_DOT] = ".",
  [anon_sym_LT] = "<",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_GT] = ">",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_and] = "and",
  [anon_sym_or] = "or",
  [sym_number] = "number",
  [sym_string] = "string",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_null] = "null",
  [anon_sym_COLON] = ":",
  [anon_sym_SLASH_SLASH] = "//",
  [aux_sym_comment_token1] = "comment_token1",
  [sym_source_file] = "source_file",
  [sym__declaration] = "_declaration",
  [sym_varDeclaration] = "varDeclaration",
  [sym__statement] = "_statement",
  [sym__block] = "_block",
  [sym_ifStatement] = "ifStatement",
  [sym_expressionStatement] = "expressionStatement",
  [sym_printStatement] = "printStatement",
  [sym__expression] = "_expression",
  [sym_unary] = "unary",
  [sym_binary] = "binary",
  [sym_comparison] = "comparison",
  [sym_equality] = "equality",
  [sym_logical] = "logical",
  [sym_assignment] = "assignment",
  [sym__primary] = "_primary",
  [sym_bool] = "bool",
  [sym__typeHint] = "_typeHint",
  [sym_comment] = "comment",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym__block_repeat1] = "_block_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_var] = anon_sym_var,
  [anon_sym_const] = anon_sym_const,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_else] = anon_sym_else,
  [anon_sym_print] = anon_sym_print,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_and] = anon_sym_and,
  [anon_sym_or] = anon_sym_or,
  [sym_number] = sym_number,
  [sym_string] = sym_string,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_null] = sym_null,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_SLASH_SLASH] = anon_sym_SLASH_SLASH,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [sym_source_file] = sym_source_file,
  [sym__declaration] = sym__declaration,
  [sym_varDeclaration] = sym_varDeclaration,
  [sym__statement] = sym__statement,
  [sym__block] = sym__block,
  [sym_ifStatement] = sym_ifStatement,
  [sym_expressionStatement] = sym_expressionStatement,
  [sym_printStatement] = sym_printStatement,
  [sym__expression] = sym__expression,
  [sym_unary] = sym_unary,
  [sym_binary] = sym_binary,
  [sym_comparison] = sym_comparison,
  [sym_equality] = sym_equality,
  [sym_logical] = sym_logical,
  [sym_assignment] = sym_assignment,
  [sym__primary] = sym__primary,
  [sym_bool] = sym_bool,
  [sym__typeHint] = sym__typeHint,
  [sym_comment] = sym_comment,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym__block_repeat1] = aux_sym__block_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_var] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_const] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_print] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_and] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_or] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_null] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_SLASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__declaration] = {
    .visible = false,
    .named = true,
  },
  [sym_varDeclaration] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym__block] = {
    .visible = false,
    .named = true,
  },
  [sym_ifStatement] = {
    .visible = true,
    .named = true,
  },
  [sym_expressionStatement] = {
    .visible = true,
    .named = true,
  },
  [sym_printStatement] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_unary] = {
    .visible = true,
    .named = true,
  },
  [sym_binary] = {
    .visible = true,
    .named = true,
  },
  [sym_comparison] = {
    .visible = true,
    .named = true,
  },
  [sym_equality] = {
    .visible = true,
    .named = true,
  },
  [sym_logical] = {
    .visible = true,
    .named = true,
  },
  [sym_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym__primary] = {
    .visible = false,
    .named = true,
  },
  [sym_bool] = {
    .visible = true,
    .named = true,
  },
  [sym__typeHint] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__block_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 2,
  [4] = 2,
  [5] = 2,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 8,
  [12] = 10,
  [13] = 13,
  [14] = 14,
  [15] = 13,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 41,
  [43] = 43,
  [44] = 41,
  [45] = 37,
  [46] = 41,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 47,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 55,
  [65] = 65,
  [66] = 62,
  [67] = 47,
  [68] = 48,
  [69] = 52,
  [70] = 49,
  [71] = 50,
  [72] = 54,
  [73] = 51,
  [74] = 47,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(3);
      ADVANCE_MAP(
        '!', 9,
        '"', 1,
        '*', 11,
        '+', 12,
        '-', 8,
        '.', 13,
        '/', 10,
        ':', 24,
        ';', 5,
        '<', 14,
        '=', 4,
        '>', 17,
        '{', 6,
        '}', 7,
      );
      if (lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(20);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(22);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(21);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(19);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_BANG);
      if (lookahead == '=') ADVANCE(18);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '/') ADVANCE(25);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(15);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(16);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(29);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '/') ADVANCE(28);
      if (lookahead == '\r' ||
          lookahead == ' ') ADVANCE(27);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(29);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '/') ADVANCE(26);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(29);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(29);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ADVANCE_MAP(
        'a', 1,
        'c', 2,
        'e', 3,
        'f', 4,
        'i', 5,
        'n', 6,
        'o', 7,
        'p', 8,
        't', 9,
        'v', 10,
      );
      if (lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'n') ADVANCE(11);
      END_STATE();
    case 2:
      if (lookahead == 'o') ADVANCE(12);
      END_STATE();
    case 3:
      if (lookahead == 'l') ADVANCE(13);
      END_STATE();
    case 4:
      if (lookahead == 'a') ADVANCE(14);
      END_STATE();
    case 5:
      if (lookahead == 'f') ADVANCE(15);
      END_STATE();
    case 6:
      if (lookahead == 'u') ADVANCE(16);
      END_STATE();
    case 7:
      if (lookahead == 'r') ADVANCE(17);
      END_STATE();
    case 8:
      if (lookahead == 'r') ADVANCE(18);
      END_STATE();
    case 9:
      if (lookahead == 'r') ADVANCE(19);
      END_STATE();
    case 10:
      if (lookahead == 'a') ADVANCE(20);
      END_STATE();
    case 11:
      if (lookahead == 'd') ADVANCE(21);
      END_STATE();
    case 12:
      if (lookahead == 'n') ADVANCE(22);
      END_STATE();
    case 13:
      if (lookahead == 's') ADVANCE(23);
      END_STATE();
    case 14:
      if (lookahead == 'l') ADVANCE(24);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 16:
      if (lookahead == 'l') ADVANCE(25);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_or);
      END_STATE();
    case 18:
      if (lookahead == 'i') ADVANCE(26);
      END_STATE();
    case 19:
      if (lookahead == 'u') ADVANCE(27);
      END_STATE();
    case 20:
      if (lookahead == 'r') ADVANCE(28);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_and);
      END_STATE();
    case 22:
      if (lookahead == 's') ADVANCE(29);
      END_STATE();
    case 23:
      if (lookahead == 'e') ADVANCE(30);
      END_STATE();
    case 24:
      if (lookahead == 's') ADVANCE(31);
      END_STATE();
    case 25:
      if (lookahead == 'l') ADVANCE(32);
      END_STATE();
    case 26:
      if (lookahead == 'n') ADVANCE(33);
      END_STATE();
    case 27:
      if (lookahead == 'e') ADVANCE(34);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_var);
      END_STATE();
    case 29:
      if (lookahead == 't') ADVANCE(35);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_else);
      END_STATE();
    case 31:
      if (lookahead == 'e') ADVANCE(36);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_null);
      END_STATE();
    case 33:
      if (lookahead == 't') ADVANCE(37);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_const);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_print);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 27},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {(TSStateId)(-1)},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [sym_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_var] = ACTIONS(1),
    [anon_sym_const] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [anon_sym_print] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_and] = ACTIONS(1),
    [anon_sym_or] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_null] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
  [1] = {
    [sym_source_file] = STATE(82),
    [sym__declaration] = STATE(65),
    [sym_varDeclaration] = STATE(63),
    [sym__statement] = STATE(63),
    [sym__block] = STATE(52),
    [sym_ifStatement] = STATE(52),
    [sym_expressionStatement] = STATE(52),
    [sym_printStatement] = STATE(52),
    [sym__expression] = STATE(55),
    [sym_unary] = STATE(17),
    [sym_binary] = STATE(17),
    [sym_comparison] = STATE(17),
    [sym_equality] = STATE(17),
    [sym_logical] = STATE(17),
    [sym_assignment] = STATE(17),
    [sym__primary] = STATE(17),
    [sym_bool] = STATE(28),
    [sym_comment] = STATE(1),
    [aux_sym_source_file_repeat1] = STATE(7),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_identifier] = ACTIONS(7),
    [anon_sym_var] = ACTIONS(9),
    [anon_sym_const] = ACTIONS(9),
    [anon_sym_LBRACE] = ACTIONS(11),
    [anon_sym_if] = ACTIONS(13),
    [anon_sym_print] = ACTIONS(15),
    [anon_sym_DASH] = ACTIONS(17),
    [anon_sym_BANG] = ACTIONS(17),
    [sym_number] = ACTIONS(19),
    [sym_string] = ACTIONS(19),
    [anon_sym_true] = ACTIONS(21),
    [anon_sym_false] = ACTIONS(21),
    [sym_null] = ACTIONS(23),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
  [2] = {
    [sym__statement] = STATE(67),
    [sym__block] = STATE(69),
    [sym_ifStatement] = STATE(69),
    [sym_expressionStatement] = STATE(69),
    [sym_printStatement] = STATE(69),
    [sym__expression] = STATE(64),
    [sym_unary] = STATE(17),
    [sym_binary] = STATE(17),
    [sym_comparison] = STATE(17),
    [sym_equality] = STATE(17),
    [sym_logical] = STATE(17),
    [sym_assignment] = STATE(17),
    [sym__primary] = STATE(17),
    [sym_bool] = STATE(28),
    [sym_comment] = STATE(2),
    [sym_identifier] = ACTIONS(7),
    [anon_sym_LBRACE] = ACTIONS(25),
    [anon_sym_if] = ACTIONS(27),
    [anon_sym_print] = ACTIONS(29),
    [anon_sym_DASH] = ACTIONS(31),
    [anon_sym_BANG] = ACTIONS(33),
    [anon_sym_SLASH] = ACTIONS(35),
    [anon_sym_STAR] = ACTIONS(37),
    [anon_sym_PLUS] = ACTIONS(39),
    [anon_sym_DOT] = ACTIONS(41),
    [anon_sym_LT] = ACTIONS(43),
    [anon_sym_LT_EQ] = ACTIONS(45),
    [anon_sym_GT_EQ] = ACTIONS(45),
    [anon_sym_GT] = ACTIONS(43),
    [anon_sym_BANG_EQ] = ACTIONS(47),
    [anon_sym_EQ_EQ] = ACTIONS(47),
    [anon_sym_and] = ACTIONS(49),
    [anon_sym_or] = ACTIONS(51),
    [sym_number] = ACTIONS(19),
    [sym_string] = ACTIONS(19),
    [anon_sym_true] = ACTIONS(21),
    [anon_sym_false] = ACTIONS(21),
    [sym_null] = ACTIONS(23),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
  [3] = {
    [sym__statement] = STATE(74),
    [sym__block] = STATE(69),
    [sym_ifStatement] = STATE(69),
    [sym_expressionStatement] = STATE(69),
    [sym_printStatement] = STATE(69),
    [sym__expression] = STATE(64),
    [sym_unary] = STATE(17),
    [sym_binary] = STATE(17),
    [sym_comparison] = STATE(17),
    [sym_equality] = STATE(17),
    [sym_logical] = STATE(17),
    [sym_assignment] = STATE(17),
    [sym__primary] = STATE(17),
    [sym_bool] = STATE(28),
    [sym_comment] = STATE(3),
    [sym_identifier] = ACTIONS(7),
    [anon_sym_LBRACE] = ACTIONS(25),
    [anon_sym_if] = ACTIONS(27),
    [anon_sym_print] = ACTIONS(29),
    [anon_sym_DASH] = ACTIONS(31),
    [anon_sym_BANG] = ACTIONS(33),
    [anon_sym_SLASH] = ACTIONS(35),
    [anon_sym_STAR] = ACTIONS(37),
    [anon_sym_PLUS] = ACTIONS(39),
    [anon_sym_DOT] = ACTIONS(41),
    [anon_sym_LT] = ACTIONS(43),
    [anon_sym_LT_EQ] = ACTIONS(45),
    [anon_sym_GT_EQ] = ACTIONS(45),
    [anon_sym_GT] = ACTIONS(43),
    [anon_sym_BANG_EQ] = ACTIONS(47),
    [anon_sym_EQ_EQ] = ACTIONS(47),
    [anon_sym_and] = ACTIONS(49),
    [anon_sym_or] = ACTIONS(51),
    [sym_number] = ACTIONS(19),
    [sym_string] = ACTIONS(19),
    [anon_sym_true] = ACTIONS(21),
    [anon_sym_false] = ACTIONS(21),
    [sym_null] = ACTIONS(23),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
  [4] = {
    [sym__statement] = STATE(53),
    [sym__block] = STATE(52),
    [sym_ifStatement] = STATE(52),
    [sym_expressionStatement] = STATE(52),
    [sym_printStatement] = STATE(52),
    [sym__expression] = STATE(55),
    [sym_unary] = STATE(17),
    [sym_binary] = STATE(17),
    [sym_comparison] = STATE(17),
    [sym_equality] = STATE(17),
    [sym_logical] = STATE(17),
    [sym_assignment] = STATE(17),
    [sym__primary] = STATE(17),
    [sym_bool] = STATE(28),
    [sym_comment] = STATE(4),
    [sym_identifier] = ACTIONS(7),
    [anon_sym_LBRACE] = ACTIONS(11),
    [anon_sym_if] = ACTIONS(53),
    [anon_sym_print] = ACTIONS(15),
    [anon_sym_DASH] = ACTIONS(31),
    [anon_sym_BANG] = ACTIONS(33),
    [anon_sym_SLASH] = ACTIONS(35),
    [anon_sym_STAR] = ACTIONS(37),
    [anon_sym_PLUS] = ACTIONS(39),
    [anon_sym_DOT] = ACTIONS(41),
    [anon_sym_LT] = ACTIONS(43),
    [anon_sym_LT_EQ] = ACTIONS(45),
    [anon_sym_GT_EQ] = ACTIONS(45),
    [anon_sym_GT] = ACTIONS(43),
    [anon_sym_BANG_EQ] = ACTIONS(47),
    [anon_sym_EQ_EQ] = ACTIONS(47),
    [anon_sym_and] = ACTIONS(49),
    [anon_sym_or] = ACTIONS(51),
    [sym_number] = ACTIONS(19),
    [sym_string] = ACTIONS(19),
    [anon_sym_true] = ACTIONS(21),
    [anon_sym_false] = ACTIONS(21),
    [sym_null] = ACTIONS(23),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
  [5] = {
    [sym__statement] = STATE(47),
    [sym__block] = STATE(52),
    [sym_ifStatement] = STATE(52),
    [sym_expressionStatement] = STATE(52),
    [sym_printStatement] = STATE(52),
    [sym__expression] = STATE(55),
    [sym_unary] = STATE(17),
    [sym_binary] = STATE(17),
    [sym_comparison] = STATE(17),
    [sym_equality] = STATE(17),
    [sym_logical] = STATE(17),
    [sym_assignment] = STATE(17),
    [sym__primary] = STATE(17),
    [sym_bool] = STATE(28),
    [sym_comment] = STATE(5),
    [sym_identifier] = ACTIONS(7),
    [anon_sym_LBRACE] = ACTIONS(11),
    [anon_sym_if] = ACTIONS(53),
    [anon_sym_print] = ACTIONS(15),
    [anon_sym_DASH] = ACTIONS(31),
    [anon_sym_BANG] = ACTIONS(33),
    [anon_sym_SLASH] = ACTIONS(35),
    [anon_sym_STAR] = ACTIONS(37),
    [anon_sym_PLUS] = ACTIONS(39),
    [anon_sym_DOT] = ACTIONS(41),
    [anon_sym_LT] = ACTIONS(43),
    [anon_sym_LT_EQ] = ACTIONS(45),
    [anon_sym_GT_EQ] = ACTIONS(45),
    [anon_sym_GT] = ACTIONS(43),
    [anon_sym_BANG_EQ] = ACTIONS(47),
    [anon_sym_EQ_EQ] = ACTIONS(47),
    [anon_sym_and] = ACTIONS(49),
    [anon_sym_or] = ACTIONS(51),
    [sym_number] = ACTIONS(19),
    [sym_string] = ACTIONS(19),
    [anon_sym_true] = ACTIONS(21),
    [anon_sym_false] = ACTIONS(21),
    [sym_null] = ACTIONS(23),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
  [6] = {
    [sym__declaration] = STATE(65),
    [sym_varDeclaration] = STATE(63),
    [sym__statement] = STATE(63),
    [sym__block] = STATE(52),
    [sym_ifStatement] = STATE(52),
    [sym_expressionStatement] = STATE(52),
    [sym_printStatement] = STATE(52),
    [sym__expression] = STATE(55),
    [sym_unary] = STATE(17),
    [sym_binary] = STATE(17),
    [sym_comparison] = STATE(17),
    [sym_equality] = STATE(17),
    [sym_logical] = STATE(17),
    [sym_assignment] = STATE(17),
    [sym__primary] = STATE(17),
    [sym_bool] = STATE(28),
    [sym_comment] = STATE(6),
    [aux_sym_source_file_repeat1] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(55),
    [sym_identifier] = ACTIONS(57),
    [anon_sym_var] = ACTIONS(60),
    [anon_sym_const] = ACTIONS(60),
    [anon_sym_LBRACE] = ACTIONS(63),
    [anon_sym_if] = ACTIONS(66),
    [anon_sym_print] = ACTIONS(69),
    [anon_sym_DASH] = ACTIONS(72),
    [anon_sym_BANG] = ACTIONS(72),
    [sym_number] = ACTIONS(75),
    [sym_string] = ACTIONS(75),
    [anon_sym_true] = ACTIONS(78),
    [anon_sym_false] = ACTIONS(78),
    [sym_null] = ACTIONS(81),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
  [7] = {
    [sym__declaration] = STATE(65),
    [sym_varDeclaration] = STATE(63),
    [sym__statement] = STATE(63),
    [sym__block] = STATE(52),
    [sym_ifStatement] = STATE(52),
    [sym_expressionStatement] = STATE(52),
    [sym_printStatement] = STATE(52),
    [sym__expression] = STATE(55),
    [sym_unary] = STATE(17),
    [sym_binary] = STATE(17),
    [sym_comparison] = STATE(17),
    [sym_equality] = STATE(17),
    [sym_logical] = STATE(17),
    [sym_assignment] = STATE(17),
    [sym__primary] = STATE(17),
    [sym_bool] = STATE(28),
    [sym_comment] = STATE(7),
    [aux_sym_source_file_repeat1] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(84),
    [sym_identifier] = ACTIONS(7),
    [anon_sym_var] = ACTIONS(9),
    [anon_sym_const] = ACTIONS(9),
    [anon_sym_LBRACE] = ACTIONS(11),
    [anon_sym_if] = ACTIONS(13),
    [anon_sym_print] = ACTIONS(15),
    [anon_sym_DASH] = ACTIONS(17),
    [anon_sym_BANG] = ACTIONS(17),
    [sym_number] = ACTIONS(19),
    [sym_string] = ACTIONS(19),
    [anon_sym_true] = ACTIONS(21),
    [anon_sym_false] = ACTIONS(21),
    [sym_null] = ACTIONS(23),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
  [8] = {
    [sym__statement] = STATE(75),
    [sym__block] = STATE(69),
    [sym_ifStatement] = STATE(69),
    [sym_expressionStatement] = STATE(69),
    [sym_printStatement] = STATE(69),
    [sym__expression] = STATE(64),
    [sym_unary] = STATE(17),
    [sym_binary] = STATE(17),
    [sym_comparison] = STATE(17),
    [sym_equality] = STATE(17),
    [sym_logical] = STATE(17),
    [sym_assignment] = STATE(17),
    [sym__primary] = STATE(17),
    [sym_bool] = STATE(28),
    [sym_comment] = STATE(8),
    [aux_sym__block_repeat1] = STATE(9),
    [sym_identifier] = ACTIONS(7),
    [anon_sym_LBRACE] = ACTIONS(25),
    [anon_sym_RBRACE] = ACTIONS(86),
    [anon_sym_if] = ACTIONS(88),
    [anon_sym_print] = ACTIONS(29),
    [anon_sym_DASH] = ACTIONS(17),
    [anon_sym_BANG] = ACTIONS(17),
    [sym_number] = ACTIONS(19),
    [sym_string] = ACTIONS(19),
    [anon_sym_true] = ACTIONS(21),
    [anon_sym_false] = ACTIONS(21),
    [sym_null] = ACTIONS(23),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
  [9] = {
    [sym__statement] = STATE(75),
    [sym__block] = STATE(69),
    [sym_ifStatement] = STATE(69),
    [sym_expressionStatement] = STATE(69),
    [sym_printStatement] = STATE(69),
    [sym__expression] = STATE(64),
    [sym_unary] = STATE(17),
    [sym_binary] = STATE(17),
    [sym_comparison] = STATE(17),
    [sym_equality] = STATE(17),
    [sym_logical] = STATE(17),
    [sym_assignment] = STATE(17),
    [sym__primary] = STATE(17),
    [sym_bool] = STATE(28),
    [sym_comment] = STATE(9),
    [aux_sym__block_repeat1] = STATE(9),
    [sym_identifier] = ACTIONS(90),
    [anon_sym_LBRACE] = ACTIONS(93),
    [anon_sym_RBRACE] = ACTIONS(96),
    [anon_sym_if] = ACTIONS(98),
    [anon_sym_print] = ACTIONS(101),
    [anon_sym_DASH] = ACTIONS(104),
    [anon_sym_BANG] = ACTIONS(104),
    [sym_number] = ACTIONS(107),
    [sym_string] = ACTIONS(107),
    [anon_sym_true] = ACTIONS(110),
    [anon_sym_false] = ACTIONS(110),
    [sym_null] = ACTIONS(113),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
  [10] = {
    [sym__statement] = STATE(75),
    [sym__block] = STATE(69),
    [sym_ifStatement] = STATE(69),
    [sym_expressionStatement] = STATE(69),
    [sym_printStatement] = STATE(69),
    [sym__expression] = STATE(64),
    [sym_unary] = STATE(17),
    [sym_binary] = STATE(17),
    [sym_comparison] = STATE(17),
    [sym_equality] = STATE(17),
    [sym_logical] = STATE(17),
    [sym_assignment] = STATE(17),
    [sym__primary] = STATE(17),
    [sym_bool] = STATE(28),
    [sym_comment] = STATE(10),
    [aux_sym__block_repeat1] = STATE(11),
    [sym_identifier] = ACTIONS(7),
    [anon_sym_LBRACE] = ACTIONS(25),
    [anon_sym_RBRACE] = ACTIONS(116),
    [anon_sym_if] = ACTIONS(88),
    [anon_sym_print] = ACTIONS(29),
    [anon_sym_DASH] = ACTIONS(17),
    [anon_sym_BANG] = ACTIONS(17),
    [sym_number] = ACTIONS(19),
    [sym_string] = ACTIONS(19),
    [anon_sym_true] = ACTIONS(21),
    [anon_sym_false] = ACTIONS(21),
    [sym_null] = ACTIONS(23),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
  [11] = {
    [sym__statement] = STATE(75),
    [sym__block] = STATE(69),
    [sym_ifStatement] = STATE(69),
    [sym_expressionStatement] = STATE(69),
    [sym_printStatement] = STATE(69),
    [sym__expression] = STATE(64),
    [sym_unary] = STATE(17),
    [sym_binary] = STATE(17),
    [sym_comparison] = STATE(17),
    [sym_equality] = STATE(17),
    [sym_logical] = STATE(17),
    [sym_assignment] = STATE(17),
    [sym__primary] = STATE(17),
    [sym_bool] = STATE(28),
    [sym_comment] = STATE(11),
    [aux_sym__block_repeat1] = STATE(9),
    [sym_identifier] = ACTIONS(7),
    [anon_sym_LBRACE] = ACTIONS(25),
    [anon_sym_RBRACE] = ACTIONS(118),
    [anon_sym_if] = ACTIONS(88),
    [anon_sym_print] = ACTIONS(29),
    [anon_sym_DASH] = ACTIONS(17),
    [anon_sym_BANG] = ACTIONS(17),
    [sym_number] = ACTIONS(19),
    [sym_string] = ACTIONS(19),
    [anon_sym_true] = ACTIONS(21),
    [anon_sym_false] = ACTIONS(21),
    [sym_null] = ACTIONS(23),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
  [12] = {
    [sym__statement] = STATE(75),
    [sym__block] = STATE(69),
    [sym_ifStatement] = STATE(69),
    [sym_expressionStatement] = STATE(69),
    [sym_printStatement] = STATE(69),
    [sym__expression] = STATE(64),
    [sym_unary] = STATE(17),
    [sym_binary] = STATE(17),
    [sym_comparison] = STATE(17),
    [sym_equality] = STATE(17),
    [sym_logical] = STATE(17),
    [sym_assignment] = STATE(17),
    [sym__primary] = STATE(17),
    [sym_bool] = STATE(28),
    [sym_comment] = STATE(12),
    [aux_sym__block_repeat1] = STATE(8),
    [sym_identifier] = ACTIONS(7),
    [anon_sym_LBRACE] = ACTIONS(25),
    [anon_sym_RBRACE] = ACTIONS(120),
    [anon_sym_if] = ACTIONS(88),
    [anon_sym_print] = ACTIONS(29),
    [anon_sym_DASH] = ACTIONS(17),
    [anon_sym_BANG] = ACTIONS(17),
    [sym_number] = ACTIONS(19),
    [sym_string] = ACTIONS(19),
    [anon_sym_true] = ACTIONS(21),
    [anon_sym_false] = ACTIONS(21),
    [sym_null] = ACTIONS(23),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 15,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(23), 1,
      sym_null,
    ACTIONS(25), 1,
      anon_sym_LBRACE,
    ACTIONS(29), 1,
      anon_sym_print,
    ACTIONS(88), 1,
      anon_sym_if,
    STATE(13), 1,
      sym_comment,
    STATE(28), 1,
      sym_bool,
    STATE(64), 1,
      sym__expression,
    STATE(73), 1,
      sym__statement,
    ACTIONS(17), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(19), 2,
      sym_number,
      sym_string,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(69), 4,
      sym__block,
      sym_ifStatement,
      sym_expressionStatement,
      sym_printStatement,
    STATE(17), 7,
      sym_unary,
      sym_binary,
      sym_comparison,
      sym_equality,
      sym_logical,
      sym_assignment,
      sym__primary,
  [58] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(124), 1,
      anon_sym_EQ,
    STATE(14), 1,
      sym_comment,
    ACTIONS(122), 12,
      anon_sym_if,
      anon_sym_print,
      anon_sym_BANG,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_and,
      anon_sym_or,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_identifier,
    ACTIONS(126), 12,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DOT,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      sym_number,
      sym_string,
  [96] = 15,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_if,
    ACTIONS(15), 1,
      anon_sym_print,
    ACTIONS(23), 1,
      sym_null,
    STATE(15), 1,
      sym_comment,
    STATE(28), 1,
      sym_bool,
    STATE(51), 1,
      sym__statement,
    STATE(55), 1,
      sym__expression,
    ACTIONS(17), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(19), 2,
      sym_number,
      sym_string,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(52), 4,
      sym__block,
      sym_ifStatement,
      sym_expressionStatement,
      sym_printStatement,
    STATE(17), 7,
      sym_unary,
      sym_binary,
      sym_comparison,
      sym_equality,
      sym_logical,
      sym_assignment,
      sym__primary,
  [154] = 13,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(35), 1,
      anon_sym_SLASH,
    ACTIONS(37), 1,
      anon_sym_STAR,
    ACTIONS(41), 1,
      anon_sym_DOT,
    ACTIONS(49), 1,
      anon_sym_and,
    ACTIONS(51), 1,
      anon_sym_or,
    STATE(16), 1,
      sym_comment,
    ACTIONS(39), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(43), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(45), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(47), 2,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
    ACTIONS(130), 4,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      sym_number,
      sym_string,
    ACTIONS(128), 7,
      anon_sym_if,
      anon_sym_print,
      anon_sym_BANG,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_identifier,
  [207] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(17), 1,
      sym_comment,
    ACTIONS(132), 12,
      anon_sym_if,
      anon_sym_print,
      anon_sym_BANG,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_and,
      anon_sym_or,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_identifier,
    ACTIONS(134), 12,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DOT,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      sym_number,
      sym_string,
  [242] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(35), 1,
      anon_sym_SLASH,
    ACTIONS(37), 1,
      anon_sym_STAR,
    STATE(18), 1,
      sym_comment,
    ACTIONS(136), 11,
      anon_sym_if,
      anon_sym_print,
      anon_sym_BANG,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_and,
      anon_sym_or,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_identifier,
    ACTIONS(138), 11,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_DOT,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      sym_number,
      sym_string,
  [281] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(19), 1,
      sym_comment,
    ACTIONS(136), 12,
      anon_sym_if,
      anon_sym_print,
      anon_sym_BANG,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_and,
      anon_sym_or,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_identifier,
    ACTIONS(138), 12,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DOT,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      sym_number,
      sym_string,
  [316] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(35), 1,
      anon_sym_SLASH,
    ACTIONS(37), 1,
      anon_sym_STAR,
    ACTIONS(49), 1,
      anon_sym_and,
    ACTIONS(51), 1,
      anon_sym_or,
    STATE(20), 1,
      sym_comment,
    ACTIONS(39), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(43), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(45), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(47), 2,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
    ACTIONS(138), 5,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_DOT,
      sym_number,
      sym_string,
    ACTIONS(136), 7,
      anon_sym_if,
      anon_sym_print,
      anon_sym_BANG,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_identifier,
  [367] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(35), 1,
      anon_sym_SLASH,
    ACTIONS(37), 1,
      anon_sym_STAR,
    STATE(21), 1,
      sym_comment,
    ACTIONS(39), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(142), 9,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_DOT,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      sym_number,
      sym_string,
    ACTIONS(140), 11,
      anon_sym_if,
      anon_sym_print,
      anon_sym_BANG,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_and,
      anon_sym_or,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_identifier,
  [408] = 9,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(35), 1,
      anon_sym_SLASH,
    ACTIONS(37), 1,
      anon_sym_STAR,
    STATE(22), 1,
      sym_comment,
    ACTIONS(39), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(43), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(45), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(146), 7,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_DOT,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      sym_number,
      sym_string,
    ACTIONS(144), 9,
      anon_sym_if,
      anon_sym_print,
      anon_sym_BANG,
      anon_sym_and,
      anon_sym_or,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_identifier,
  [453] = 10,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(35), 1,
      anon_sym_SLASH,
    ACTIONS(37), 1,
      anon_sym_STAR,
    STATE(23), 1,
      sym_comment,
    ACTIONS(39), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(43), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(45), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(47), 2,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
    ACTIONS(150), 5,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_DOT,
      sym_number,
      sym_string,
    ACTIONS(148), 9,
      anon_sym_if,
      anon_sym_print,
      anon_sym_BANG,
      anon_sym_and,
      anon_sym_or,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_identifier,
  [500] = 11,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(35), 1,
      anon_sym_SLASH,
    ACTIONS(37), 1,
      anon_sym_STAR,
    ACTIONS(49), 1,
      anon_sym_and,
    STATE(24), 1,
      sym_comment,
    ACTIONS(39), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(43), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(45), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(47), 2,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
    ACTIONS(150), 5,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_DOT,
      sym_number,
      sym_string,
    ACTIONS(148), 8,
      anon_sym_if,
      anon_sym_print,
      anon_sym_BANG,
      anon_sym_or,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_identifier,
  [549] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(25), 1,
      sym_comment,
    ACTIONS(152), 12,
      anon_sym_if,
      anon_sym_print,
      anon_sym_BANG,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_and,
      anon_sym_or,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_identifier,
    ACTIONS(154), 12,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DOT,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      sym_number,
      sym_string,
  [584] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(26), 1,
      sym_comment,
    ACTIONS(138), 3,
      anon_sym_LBRACE,
      sym_number,
      sym_string,
    ACTIONS(152), 5,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_and,
      anon_sym_or,
    ACTIONS(136), 7,
      anon_sym_if,
      anon_sym_print,
      anon_sym_BANG,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_identifier,
    ACTIONS(154), 9,
      anon_sym_SEMI,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DOT,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
  [623] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(27), 1,
      sym_comment,
    ACTIONS(156), 12,
      anon_sym_if,
      anon_sym_print,
      anon_sym_BANG,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_and,
      anon_sym_or,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_identifier,
    ACTIONS(158), 12,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DOT,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      sym_number,
      sym_string,
  [658] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(28), 1,
      sym_comment,
    ACTIONS(122), 12,
      anon_sym_if,
      anon_sym_print,
      anon_sym_BANG,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_and,
      anon_sym_or,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_identifier,
    ACTIONS(126), 12,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DOT,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      sym_number,
      sym_string,
  [693] = 10,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(23), 1,
      sym_null,
    STATE(16), 1,
      sym__expression,
    STATE(28), 1,
      sym_bool,
    STATE(29), 1,
      sym_comment,
    ACTIONS(17), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(19), 2,
      sym_number,
      sym_string,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(17), 7,
      sym_unary,
      sym_binary,
      sym_comparison,
      sym_equality,
      sym_logical,
      sym_assignment,
      sym__primary,
  [733] = 10,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(23), 1,
      sym_null,
    STATE(18), 1,
      sym__expression,
    STATE(28), 1,
      sym_bool,
    STATE(30), 1,
      sym_comment,
    ACTIONS(17), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(19), 2,
      sym_number,
      sym_string,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(17), 7,
      sym_unary,
      sym_binary,
      sym_comparison,
      sym_equality,
      sym_logical,
      sym_assignment,
      sym__primary,
  [773] = 10,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(23), 1,
      sym_null,
    STATE(19), 1,
      sym__expression,
    STATE(28), 1,
      sym_bool,
    STATE(31), 1,
      sym_comment,
    ACTIONS(17), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(19), 2,
      sym_number,
      sym_string,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(17), 7,
      sym_unary,
      sym_binary,
      sym_comparison,
      sym_equality,
      sym_logical,
      sym_assignment,
      sym__primary,
  [813] = 10,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(23), 1,
      sym_null,
    STATE(20), 1,
      sym__expression,
    STATE(28), 1,
      sym_bool,
    STATE(32), 1,
      sym_comment,
    ACTIONS(17), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(19), 2,
      sym_number,
      sym_string,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(17), 7,
      sym_unary,
      sym_binary,
      sym_comparison,
      sym_equality,
      sym_logical,
      sym_assignment,
      sym__primary,
  [853] = 10,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(23), 1,
      sym_null,
    STATE(21), 1,
      sym__expression,
    STATE(28), 1,
      sym_bool,
    STATE(33), 1,
      sym_comment,
    ACTIONS(17), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(19), 2,
      sym_number,
      sym_string,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(17), 7,
      sym_unary,
      sym_binary,
      sym_comparison,
      sym_equality,
      sym_logical,
      sym_assignment,
      sym__primary,
  [893] = 10,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(23), 1,
      sym_null,
    STATE(22), 1,
      sym__expression,
    STATE(28), 1,
      sym_bool,
    STATE(34), 1,
      sym_comment,
    ACTIONS(17), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(19), 2,
      sym_number,
      sym_string,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(17), 7,
      sym_unary,
      sym_binary,
      sym_comparison,
      sym_equality,
      sym_logical,
      sym_assignment,
      sym__primary,
  [933] = 10,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(23), 1,
      sym_null,
    STATE(23), 1,
      sym__expression,
    STATE(28), 1,
      sym_bool,
    STATE(35), 1,
      sym_comment,
    ACTIONS(17), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(19), 2,
      sym_number,
      sym_string,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(17), 7,
      sym_unary,
      sym_binary,
      sym_comparison,
      sym_equality,
      sym_logical,
      sym_assignment,
      sym__primary,
  [973] = 10,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(23), 1,
      sym_null,
    STATE(24), 1,
      sym__expression,
    STATE(28), 1,
      sym_bool,
    STATE(36), 1,
      sym_comment,
    ACTIONS(17), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(19), 2,
      sym_number,
      sym_string,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(17), 7,
      sym_unary,
      sym_binary,
      sym_comparison,
      sym_equality,
      sym_logical,
      sym_assignment,
      sym__primary,
  [1013] = 10,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(23), 1,
      sym_null,
    STATE(28), 1,
      sym_bool,
    STATE(37), 1,
      sym_comment,
    STATE(66), 1,
      sym__expression,
    ACTIONS(17), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(19), 2,
      sym_number,
      sym_string,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(17), 7,
      sym_unary,
      sym_binary,
      sym_comparison,
      sym_equality,
      sym_logical,
      sym_assignment,
      sym__primary,
  [1053] = 10,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(23), 1,
      sym_null,
    STATE(28), 1,
      sym_bool,
    STATE(38), 1,
      sym_comment,
    STATE(61), 1,
      sym__expression,
    ACTIONS(17), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(19), 2,
      sym_number,
      sym_string,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(17), 7,
      sym_unary,
      sym_binary,
      sym_comparison,
      sym_equality,
      sym_logical,
      sym_assignment,
      sym__primary,
  [1093] = 10,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(23), 1,
      sym_null,
    STATE(25), 1,
      sym__expression,
    STATE(28), 1,
      sym_bool,
    STATE(39), 1,
      sym_comment,
    ACTIONS(17), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(19), 2,
      sym_number,
      sym_string,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(17), 7,
      sym_unary,
      sym_binary,
      sym_comparison,
      sym_equality,
      sym_logical,
      sym_assignment,
      sym__primary,
  [1133] = 10,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(23), 1,
      sym_null,
    STATE(26), 1,
      sym__expression,
    STATE(28), 1,
      sym_bool,
    STATE(40), 1,
      sym_comment,
    ACTIONS(17), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(19), 2,
      sym_number,
      sym_string,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(17), 7,
      sym_unary,
      sym_binary,
      sym_comparison,
      sym_equality,
      sym_logical,
      sym_assignment,
      sym__primary,
  [1173] = 10,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(23), 1,
      sym_null,
    STATE(3), 1,
      sym__expression,
    STATE(28), 1,
      sym_bool,
    STATE(41), 1,
      sym_comment,
    ACTIONS(17), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(19), 2,
      sym_number,
      sym_string,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(17), 7,
      sym_unary,
      sym_binary,
      sym_comparison,
      sym_equality,
      sym_logical,
      sym_assignment,
      sym__primary,
  [1213] = 10,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(23), 1,
      sym_null,
    STATE(4), 1,
      sym__expression,
    STATE(28), 1,
      sym_bool,
    STATE(42), 1,
      sym_comment,
    ACTIONS(17), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(19), 2,
      sym_number,
      sym_string,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(17), 7,
      sym_unary,
      sym_binary,
      sym_comparison,
      sym_equality,
      sym_logical,
      sym_assignment,
      sym__primary,
  [1253] = 10,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(23), 1,
      sym_null,
    STATE(28), 1,
      sym_bool,
    STATE(43), 1,
      sym_comment,
    STATE(60), 1,
      sym__expression,
    ACTIONS(17), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(19), 2,
      sym_number,
      sym_string,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(17), 7,
      sym_unary,
      sym_binary,
      sym_comparison,
      sym_equality,
      sym_logical,
      sym_assignment,
      sym__primary,
  [1293] = 10,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(23), 1,
      sym_null,
    STATE(2), 1,
      sym__expression,
    STATE(28), 1,
      sym_bool,
    STATE(44), 1,
      sym_comment,
    ACTIONS(17), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(19), 2,
      sym_number,
      sym_string,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(17), 7,
      sym_unary,
      sym_binary,
      sym_comparison,
      sym_equality,
      sym_logical,
      sym_assignment,
      sym__primary,
  [1333] = 10,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(23), 1,
      sym_null,
    STATE(28), 1,
      sym_bool,
    STATE(45), 1,
      sym_comment,
    STATE(62), 1,
      sym__expression,
    ACTIONS(17), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(19), 2,
      sym_number,
      sym_string,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(17), 7,
      sym_unary,
      sym_binary,
      sym_comparison,
      sym_equality,
      sym_logical,
      sym_assignment,
      sym__primary,
  [1373] = 10,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(23), 1,
      sym_null,
    STATE(5), 1,
      sym__expression,
    STATE(28), 1,
      sym_bool,
    STATE(46), 1,
      sym_comment,
    ACTIONS(17), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(19), 2,
      sym_number,
      sym_string,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(17), 7,
      sym_unary,
      sym_binary,
      sym_comparison,
      sym_equality,
      sym_logical,
      sym_assignment,
      sym__primary,
  [1413] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(47), 1,
      sym_comment,
    ACTIONS(160), 6,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
      sym_string,
    ACTIONS(162), 9,
      anon_sym_var,
      anon_sym_const,
      anon_sym_if,
      anon_sym_else,
      anon_sym_print,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_identifier,
  [1439] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(48), 1,
      sym_comment,
    ACTIONS(164), 6,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
      sym_string,
    ACTIONS(166), 9,
      anon_sym_var,
      anon_sym_const,
      anon_sym_if,
      anon_sym_else,
      anon_sym_print,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_identifier,
  [1465] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(49), 1,
      sym_comment,
    ACTIONS(168), 6,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
      sym_string,
    ACTIONS(170), 9,
      anon_sym_var,
      anon_sym_const,
      anon_sym_if,
      anon_sym_else,
      anon_sym_print,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_identifier,
  [1491] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(50), 1,
      sym_comment,
    ACTIONS(172), 6,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
      sym_string,
    ACTIONS(174), 9,
      anon_sym_var,
      anon_sym_const,
      anon_sym_if,
      anon_sym_else,
      anon_sym_print,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_identifier,
  [1517] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(51), 1,
      sym_comment,
    ACTIONS(176), 6,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
      sym_string,
    ACTIONS(178), 9,
      anon_sym_var,
      anon_sym_const,
      anon_sym_if,
      anon_sym_else,
      anon_sym_print,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_identifier,
  [1543] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(52), 1,
      sym_comment,
    ACTIONS(180), 6,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
      sym_string,
    ACTIONS(182), 9,
      anon_sym_var,
      anon_sym_const,
      anon_sym_if,
      anon_sym_else,
      anon_sym_print,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_identifier,
  [1569] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(184), 1,
      anon_sym_else,
    STATE(53), 1,
      sym_comment,
    ACTIONS(160), 6,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
      sym_string,
    ACTIONS(162), 8,
      anon_sym_var,
      anon_sym_const,
      anon_sym_if,
      anon_sym_print,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_identifier,
  [1597] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(54), 1,
      sym_comment,
    ACTIONS(186), 6,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
      sym_string,
    ACTIONS(188), 9,
      anon_sym_var,
      anon_sym_const,
      anon_sym_if,
      anon_sym_else,
      anon_sym_print,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_identifier,
  [1623] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(35), 1,
      anon_sym_SLASH,
    ACTIONS(37), 1,
      anon_sym_STAR,
    ACTIONS(41), 1,
      anon_sym_DOT,
    ACTIONS(190), 1,
      anon_sym_SEMI,
    ACTIONS(192), 1,
      anon_sym_and,
    ACTIONS(194), 1,
      anon_sym_or,
    STATE(55), 1,
      sym_comment,
    ACTIONS(39), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(43), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(45), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(47), 2,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
  [1664] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(56), 1,
      sym_comment,
    ACTIONS(196), 6,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
      sym_string,
    ACTIONS(198), 8,
      anon_sym_var,
      anon_sym_const,
      anon_sym_if,
      anon_sym_print,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_identifier,
  [1689] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(57), 1,
      sym_comment,
    ACTIONS(200), 6,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
      sym_string,
    ACTIONS(202), 8,
      anon_sym_var,
      anon_sym_const,
      anon_sym_if,
      anon_sym_print,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_identifier,
  [1714] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(58), 1,
      sym_comment,
    ACTIONS(204), 6,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
      sym_string,
    ACTIONS(206), 8,
      anon_sym_var,
      anon_sym_const,
      anon_sym_if,
      anon_sym_print,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_identifier,
  [1739] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(59), 1,
      sym_comment,
    ACTIONS(208), 6,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
      sym_string,
    ACTIONS(210), 8,
      anon_sym_var,
      anon_sym_const,
      anon_sym_if,
      anon_sym_print,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_identifier,
  [1764] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(35), 1,
      anon_sym_SLASH,
    ACTIONS(37), 1,
      anon_sym_STAR,
    ACTIONS(41), 1,
      anon_sym_DOT,
    ACTIONS(192), 1,
      anon_sym_and,
    ACTIONS(194), 1,
      anon_sym_or,
    ACTIONS(212), 1,
      anon_sym_SEMI,
    STATE(60), 1,
      sym_comment,
    ACTIONS(39), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(43), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(45), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(47), 2,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
  [1805] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(35), 1,
      anon_sym_SLASH,
    ACTIONS(37), 1,
      anon_sym_STAR,
    ACTIONS(41), 1,
      anon_sym_DOT,
    ACTIONS(192), 1,
      anon_sym_and,
    ACTIONS(194), 1,
      anon_sym_or,
    ACTIONS(214), 1,
      anon_sym_SEMI,
    STATE(61), 1,
      sym_comment,
    ACTIONS(39), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(43), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(45), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(47), 2,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
  [1846] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(35), 1,
      anon_sym_SLASH,
    ACTIONS(37), 1,
      anon_sym_STAR,
    ACTIONS(41), 1,
      anon_sym_DOT,
    ACTIONS(192), 1,
      anon_sym_and,
    ACTIONS(194), 1,
      anon_sym_or,
    ACTIONS(216), 1,
      anon_sym_SEMI,
    STATE(62), 1,
      sym_comment,
    ACTIONS(39), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(43), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(45), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(47), 2,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
  [1887] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(63), 1,
      sym_comment,
    ACTIONS(218), 6,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
      sym_string,
    ACTIONS(220), 8,
      anon_sym_var,
      anon_sym_const,
      anon_sym_if,
      anon_sym_print,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_identifier,
  [1912] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(35), 1,
      anon_sym_SLASH,
    ACTIONS(37), 1,
      anon_sym_STAR,
    ACTIONS(41), 1,
      anon_sym_DOT,
    ACTIONS(192), 1,
      anon_sym_and,
    ACTIONS(194), 1,
      anon_sym_or,
    ACTIONS(222), 1,
      anon_sym_SEMI,
    STATE(64), 1,
      sym_comment,
    ACTIONS(39), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(43), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(45), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(47), 2,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
  [1953] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(65), 1,
      sym_comment,
    ACTIONS(224), 6,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
      sym_string,
    ACTIONS(226), 8,
      anon_sym_var,
      anon_sym_const,
      anon_sym_if,
      anon_sym_print,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_identifier,
  [1978] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(35), 1,
      anon_sym_SLASH,
    ACTIONS(37), 1,
      anon_sym_STAR,
    ACTIONS(41), 1,
      anon_sym_DOT,
    ACTIONS(192), 1,
      anon_sym_and,
    ACTIONS(194), 1,
      anon_sym_or,
    ACTIONS(228), 1,
      anon_sym_SEMI,
    STATE(66), 1,
      sym_comment,
    ACTIONS(39), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(43), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(45), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(47), 2,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
  [2019] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(230), 1,
      anon_sym_else,
    STATE(67), 1,
      sym_comment,
    ACTIONS(160), 6,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
      sym_string,
    ACTIONS(162), 6,
      anon_sym_if,
      anon_sym_print,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_identifier,
  [2045] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(68), 1,
      sym_comment,
    ACTIONS(164), 6,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
      sym_string,
    ACTIONS(166), 7,
      anon_sym_if,
      anon_sym_else,
      anon_sym_print,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_identifier,
  [2069] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(69), 1,
      sym_comment,
    ACTIONS(180), 6,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
      sym_string,
    ACTIONS(182), 7,
      anon_sym_if,
      anon_sym_else,
      anon_sym_print,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_identifier,
  [2093] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(70), 1,
      sym_comment,
    ACTIONS(168), 6,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
      sym_string,
    ACTIONS(170), 7,
      anon_sym_if,
      anon_sym_else,
      anon_sym_print,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_identifier,
  [2117] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(71), 1,
      sym_comment,
    ACTIONS(172), 6,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
      sym_string,
    ACTIONS(174), 7,
      anon_sym_if,
      anon_sym_else,
      anon_sym_print,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_identifier,
  [2141] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(72), 1,
      sym_comment,
    ACTIONS(186), 6,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
      sym_string,
    ACTIONS(188), 7,
      anon_sym_if,
      anon_sym_else,
      anon_sym_print,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_identifier,
  [2165] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(73), 1,
      sym_comment,
    ACTIONS(176), 6,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
      sym_string,
    ACTIONS(178), 7,
      anon_sym_if,
      anon_sym_else,
      anon_sym_print,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_identifier,
  [2189] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(74), 1,
      sym_comment,
    ACTIONS(160), 6,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
      sym_string,
    ACTIONS(162), 7,
      anon_sym_if,
      anon_sym_else,
      anon_sym_print,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_identifier,
  [2213] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(75), 1,
      sym_comment,
    ACTIONS(232), 6,
      anon_sym_if,
      anon_sym_print,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_identifier,
    ACTIONS(234), 6,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
      sym_string,
  [2236] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(236), 1,
      anon_sym_EQ,
    ACTIONS(238), 1,
      anon_sym_SEMI,
    ACTIONS(240), 1,
      anon_sym_COLON,
    STATE(76), 1,
      sym_comment,
    STATE(78), 1,
      sym__typeHint,
  [2255] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(77), 1,
      sym_comment,
    ACTIONS(242), 2,
      anon_sym_EQ,
      anon_sym_SEMI,
  [2266] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(244), 1,
      anon_sym_EQ,
    ACTIONS(246), 1,
      anon_sym_SEMI,
    STATE(78), 1,
      sym_comment,
  [2279] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(248), 1,
      sym_identifier,
    STATE(79), 1,
      sym_comment,
  [2289] = 3,
    ACTIONS(250), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(252), 1,
      aux_sym_comment_token1,
    STATE(80), 1,
      sym_comment,
  [2299] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(254), 1,
      sym_identifier,
    STATE(81), 1,
      sym_comment,
  [2309] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(256), 1,
      ts_builtin_sym_end,
    STATE(82), 1,
      sym_comment,
  [2319] = 1,
    ACTIONS(258), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(13)] = 0,
  [SMALL_STATE(14)] = 58,
  [SMALL_STATE(15)] = 96,
  [SMALL_STATE(16)] = 154,
  [SMALL_STATE(17)] = 207,
  [SMALL_STATE(18)] = 242,
  [SMALL_STATE(19)] = 281,
  [SMALL_STATE(20)] = 316,
  [SMALL_STATE(21)] = 367,
  [SMALL_STATE(22)] = 408,
  [SMALL_STATE(23)] = 453,
  [SMALL_STATE(24)] = 500,
  [SMALL_STATE(25)] = 549,
  [SMALL_STATE(26)] = 584,
  [SMALL_STATE(27)] = 623,
  [SMALL_STATE(28)] = 658,
  [SMALL_STATE(29)] = 693,
  [SMALL_STATE(30)] = 733,
  [SMALL_STATE(31)] = 773,
  [SMALL_STATE(32)] = 813,
  [SMALL_STATE(33)] = 853,
  [SMALL_STATE(34)] = 893,
  [SMALL_STATE(35)] = 933,
  [SMALL_STATE(36)] = 973,
  [SMALL_STATE(37)] = 1013,
  [SMALL_STATE(38)] = 1053,
  [SMALL_STATE(39)] = 1093,
  [SMALL_STATE(40)] = 1133,
  [SMALL_STATE(41)] = 1173,
  [SMALL_STATE(42)] = 1213,
  [SMALL_STATE(43)] = 1253,
  [SMALL_STATE(44)] = 1293,
  [SMALL_STATE(45)] = 1333,
  [SMALL_STATE(46)] = 1373,
  [SMALL_STATE(47)] = 1413,
  [SMALL_STATE(48)] = 1439,
  [SMALL_STATE(49)] = 1465,
  [SMALL_STATE(50)] = 1491,
  [SMALL_STATE(51)] = 1517,
  [SMALL_STATE(52)] = 1543,
  [SMALL_STATE(53)] = 1569,
  [SMALL_STATE(54)] = 1597,
  [SMALL_STATE(55)] = 1623,
  [SMALL_STATE(56)] = 1664,
  [SMALL_STATE(57)] = 1689,
  [SMALL_STATE(58)] = 1714,
  [SMALL_STATE(59)] = 1739,
  [SMALL_STATE(60)] = 1764,
  [SMALL_STATE(61)] = 1805,
  [SMALL_STATE(62)] = 1846,
  [SMALL_STATE(63)] = 1887,
  [SMALL_STATE(64)] = 1912,
  [SMALL_STATE(65)] = 1953,
  [SMALL_STATE(66)] = 1978,
  [SMALL_STATE(67)] = 2019,
  [SMALL_STATE(68)] = 2045,
  [SMALL_STATE(69)] = 2069,
  [SMALL_STATE(70)] = 2093,
  [SMALL_STATE(71)] = 2117,
  [SMALL_STATE(72)] = 2141,
  [SMALL_STATE(73)] = 2165,
  [SMALL_STATE(74)] = 2189,
  [SMALL_STATE(75)] = 2213,
  [SMALL_STATE(76)] = 2236,
  [SMALL_STATE(77)] = 2255,
  [SMALL_STATE(78)] = 2266,
  [SMALL_STATE(79)] = 2279,
  [SMALL_STATE(80)] = 2289,
  [SMALL_STATE(81)] = 2299,
  [SMALL_STATE(82)] = 2309,
  [SMALL_STATE(83)] = 2319,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(81),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [43] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [49] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [51] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [53] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [57] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [60] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(81),
  [63] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [66] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(42),
  [69] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(37),
  [72] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(39),
  [75] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [78] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [81] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [88] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [90] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__block_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [93] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__block_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__block_repeat1, 2, 0, 0),
  [98] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__block_repeat1, 2, 0, 0), SHIFT_REPEAT(44),
  [101] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__block_repeat1, 2, 0, 0), SHIFT_REPEAT(45),
  [104] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__block_repeat1, 2, 0, 0), SHIFT_REPEAT(39),
  [107] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__block_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [110] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__block_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [113] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__block_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [122] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__primary, 1, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__primary, 1, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assignment, 3, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment, 3, 0, 0),
  [132] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expression, 1, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 1, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary, 3, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary, 3, 0, 0),
  [140] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comparison, 3, 0, 0),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comparison, 3, 0, 0),
  [144] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_equality, 3, 0, 0),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_equality, 3, 0, 0),
  [148] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_logical, 3, 0, 0),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_logical, 3, 0, 0),
  [152] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unary, 2, 0, 0),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unary, 2, 0, 0),
  [156] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bool, 1, 0, 0),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bool, 1, 0, 0),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ifStatement, 3, 0, 0),
  [162] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ifStatement, 3, 0, 0),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expressionStatement, 2, 0, 0),
  [166] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expressionStatement, 2, 0, 0),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__block, 2, 0, 0),
  [170] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__block, 2, 0, 0),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__block, 3, 0, 0),
  [174] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__block, 3, 0, 0),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ifStatement, 5, 0, 0),
  [178] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ifStatement, 5, 0, 0),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statement, 1, 0, 0),
  [182] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__statement, 1, 0, 0),
  [184] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_printStatement, 3, 0, 0),
  [188] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_printStatement, 3, 0, 0),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [196] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_varDeclaration, 4, 0, 0),
  [198] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_varDeclaration, 4, 0, 0),
  [200] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_varDeclaration, 3, 0, 0),
  [202] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_varDeclaration, 3, 0, 0),
  [204] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_varDeclaration, 5, 0, 0),
  [206] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_varDeclaration, 5, 0, 0),
  [208] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_varDeclaration, 6, 0, 0),
  [210] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_varDeclaration, 6, 0, 0),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [218] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__declaration, 1, 0, 0),
  [220] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__declaration, 1, 0, 0),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [224] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 0),
  [226] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 0),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [230] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [232] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__block_repeat1, 1, 0, 0),
  [234] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__block_repeat1, 1, 0, 0),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [242] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__typeHint, 2, 0, 0),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [250] = {.entry = {.count = 1, .reusable = false}}, SHIFT(80),
  [252] = {.entry = {.count = 1, .reusable = false}}, SHIFT(83),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [256] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [258] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_flow(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
